#!/usr/bin/env python3
"""
art_reel.py — price-first auction reel

Four-frame reveal — same make_reel.py pipeline:
  Frame 1 (5s)  — full artwork  · artist + title label (lower third)
  Frame 2 (2s)  — top crop      · detail view (clean)
  Frame 3 (2s)  — centre crop   · detail view (clean)
  Frame 4 (8s)  — full artwork  · data verdict (estimate / sold / %), pushed low

A voiceover explaining the painting (intro → 4-sentence art note via
ai_content.generate_hook_answer → spoken price data) is generated by default;
frame holds stretch to fit it and word-by-word captions are overlaid.
Use --no-voice for the silent ~17s cut.

Output:
  reels/{slug}/
    images/         — 3 prepared images for make_reel.py
    reel_config.py  — render config (make_reel.py reads this)
    meta.json       — lot data + social captions

Usage:
    python scripts/art_reel.py              # this week's best lot
    python scripts/art_reel.py --all-time   # best ever unposted
    python scripts/art_reel.py --artist "Basquiat"
    python scripts/art_reel.py --list       # preview candidates (no output)
    python scripts/art_reel.py --list-artists
    python scripts/art_reel.py --run        # also render video via make_reel.py
"""

import argparse
import json
import math
import os
import random
import re
import shutil
import sqlite3
import subprocess
import sys
import unicodedata
from datetime import date, timedelta
from io import BytesIO
from pathlib import Path

import httpx
from PIL import Image
from dotenv import load_dotenv

# ── Paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR   = Path(__file__).resolve().parent
BUSINESS_DIR = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))
import campaign_artist as _ca

load_dotenv(BUSINESS_DIR / ".env", override=False)

DB_PATH       = BUSINESS_DIR / "data" / "art.db"
REELS_DIR     = BUSINESS_DIR / "reels"
REEL_TEMPLATE = BUSINESS_DIR / "reel_template"
FONTS_DIR     = REEL_TEMPLATE / "fonts"

COVER_HOLD_S  = 2.0   # cover frame length; the voiceover starts right after it

# ── Notable-artist index ───────────────────────────────────────────────────────

KNOWN_ARTISTS: frozenset[str] = frozenset({
    # Abstract Expressionism
    'Franz Kline', 'Hans Hofmann',
    # Abstract Expressionism · Action Painting
    'Jackson Pollock',
    # Abstract Expressionism · Biomorphic Abstraction
    'Arshile Gorky',
    # Abstract Expressionism · Colour Field
    'Helen Frankenthaler', 'Kenneth Noland', 'Sam Francis',
    # Abstract Expressionism · Colour-Field
    'Ed Clark',
    # Abstract Expressionism · Contemporary
    'Jack Whitten', 'Louise Fishman',
    # Abstract Expressionism · Elegy Series
    'Robert Motherwell',
    # Abstract Expressionism · Hard-Edge Abstraction
    'Al Held',
    # Abstract Expressionism · Minimalism
    'Alexander Liberman',
    # Abstract Expressionism · Pictograph
    'Adolph Gottlieb',
    # Abstract Expressionism · Sculpture
    'David Smith', 'John Chamberlain', 'Louise Nevelson',
    # Abstract Expressionism · Second Generation
    'Joan Mitchell',
    # Abstract Expressionism · Women Series
    'Willem de Kooning',
    # Abstract · Colour-Field
    'Piero Dorazio',
    # Abstract · Lyrical Abstraction
    'Rhee Seundja',
    # Abstract · Modernism
    'Rudolf Bauer',
    # Abstract · Stripe Painting
    'Sean Scully',
    # Abstract · Waterfall Paintings
    'Pat Steir',
    # Abstraction · Expressionism
    'Otto Freundlich',
    # Abstraction · Figurative Modernism
    'Jean Hélion',
    # American Illustration · Social Realism
    'Norman Rockwell',
    # Art Brut · Contemporary
    'Jean Dubuffet',
    # Arte Povera · Contemporary
    'Marisa Merz',
    # Avant-Garde · Infinity · Obsessional Art
    'Yayoi Kusama',
    # Colour Field · Abstract
    'Stanley Whitney',
    # Colour-Field · Abstract Expressionism
    'Lynne Drexler', 'Sam Gilliam',
    # Conceptual Art · Minimalism
    'Sol LeWitt',
    # Conceptual Figuration · Postmodernism
    'Mark Tansey',
    # Conceptual · Contemporary
    'Adam Pendleton', 'Barbara Kruger', 'Cheyney Thompson', 'R.H. Quaytman',
    # Conceptual · Minimalism
    'Bernar Venet',
    # Conceptual · Neo-Conceptual
    'Adam McEwen',
    # Conceptual · Postmodernism
    'Sherrie Levine',
    # Contemporary Figuration · Intimacy
    'Jenna Gribbon',
    # Contemporary · Abstract
    'Günther Förg', 'Jennifer Guidi', 'Katherine Bradford', 'Kei Imazu', 'Loie Hollowell',
    'Lucy Bull', 'Mark Bradford', 'Mark Grotjahn', 'Maysha Mohamedi', 'Sadamasa Motonaga',
    'Sarah Crowner', 'Spencer Lewis',
    # Contemporary · Black American Identity
    'Rashid Johnson',
    # Contemporary · Conceptual
    'Damien Hirst', 'Hank Willis Thomas', 'Jaune Quick-to-See Smith', 'Tracey Emin',
    # Contemporary · Figurative
    'Alvin Armstrong', 'Angela Heisch', 'Asuka Anastacia Ogawa', 'Brian Calvin',
    'Caroline Walker', 'Chantal Joffe', 'Cristina de Miguel', 'Danielle McKinney',
    'Doron Langberg', 'Emmanuel Taku', 'Firenze Lai', 'Grant Yun', 'Hilary Pecis',
    'Huang Yishan', 'Ivy Haldeman', 'Izumi Kato', 'Jesse Mockrin', 'Ji Xin',
    'Joel Mesler', 'John Currin', 'Jonas Wood', 'Jonathan Lyndon Chase', 'Kehinde Wiley',
    'Ksenia Dermenzhi', 'Lisa Yuskavage', 'Liu Ye', 'María Berrío', 'Michaela Yearwood-Dan',
    'Mickalene Thomas', 'Minoru Nomata', 'Mohammed Sami', 'Philip Tsiàras', 'Qin Qi',
    'Rebecca Ness', 'Salman Toor', 'Scott Kahn', 'Shona McAndrew', 'Tyler Ballon',
    'Yu Nishimura', 'Yuan Yuan', 'Zhang Xiaogang',
    # Contemporary · Installation
    'Jim Hodges', 'Juan Muñoz', 'Katharina Grosse', 'Leonardo Drew', 'Sterling Ruby',
    # Contemporary · Minimalism
    'Maria Taniguchi',
    # Contemporary · Modernism
    'Etel Adnan',
    # Contemporary · Neo-Conceptual
    'Avery Singer',
    # Contemporary · Neo-Expressionism
    'Angel Otero', 'Genieve Figgis',
    # Contemporary · New Media
    'Christian Marclay',
    # Contemporary · Pop Art
    'Mr.', 'Takashi Murakami', 'Yoshitomo Nara',
    # Contemporary · Sculpture
    'Anish Kapoor', 'Annie Morris', 'Antony Gormley', 'Conrad Shawcross',
    'Deborah Butterfield', 'Franz West', 'Katsura Funakoshi', 'Ken Price',
    'Kohei Nawa', 'Santiago Calatrava', 'The Haas Brothers',
    # Cubism
    'Albert Gleizes', 'Jean Metzinger',
    # Cubism · Modernism
    'Pablo Picasso',
    # Cubism · Post-Impressionism
    'Henri Hayden',
    # Dada
    'Hannah Höch',
    # Dada · Surrealism
    'Man Ray',
    # Dansaekhwa · Abstract
    'Ha Chong-Hyun', 'Yun Hyong-Keun',
    # Expressionism · Der Blaue Reiter
    'Gabriele Münter',
    # Expressionism · Die Brücke
    'Karl Schmidt-Rottluff', 'Otto Mueller',
    # Expressionism · Figurative Modernism
    'Bob Thompson',
    # Fauvism · Expressionism
    'André Derain',
    # Fauvism · Modernism · Decoration
    'Henri Matisse',
    # Figurative Expressionism
    'David Park',
    # Figurative Expressionism · Bay Area Figurative
    'Joan Brown',
    # Figurative Modernism · Contemporary
    'Alex Katz',
    # Figurative Realism · Portrait
    'Alice Neel',
    # Figurative · African-American Narrative
    'Ernie Barnes',
    # German Expressionism · Die Brücke
    'Ernst Ludwig Kirchner',
    # Gutai · Contemporary
    'Takesada Matsutani',
    # Impressionism
    'Berthe Morisot',
    # Impressionism · Figure Painting
    'Pierre-Auguste Renoir',
    # Impressionism · Post-Impressionism
    'Blanche Hoschedé-Monet',
    # Impressionism · Realism
    'Edgar Degas',
    # Minimalism
    'Donald Judd',
    # Minimalism · Abstraction
    'Agnes Martin',
    # Minimalism · Contemporary
    'Blinky Palermo', 'Joel Shapiro', 'Robert Mangold', 'Robert Ryman',
    # Minimalism · Hard-Edge · Shaped Canvas
    'Frank Stella',
    # Minimalism · Process Art
    'Richard Serra',
    # Modernism · Constructivism
    'László Moholy-Nagy',
    # Modernism · Jewish Folk Tradition
    'Marc Chagall',
    # Modernism · Kinetic Sculpture
    'Alexander Calder',
    # Modernism · Minimalism
    'Josef Albers',
    # Modernism · Sculpture
    'Anthony Caro', 'Auguste Rodin', 'Camille Claudel', 'Chana Orloff',
    'Constantin Brâncuși', 'Diego Giacometti', 'Rembrandt Bugatti',
    # Neo-Conceptual · Contemporary
    'Ashley Bickerton',
    # Neo-Dada · Combines
    'Robert Rauschenberg',
    # Neo-Dada · Pop Art
    'Jim Dine',
    # Neo-Expressionism
    'Georg Baselitz',
    # Neo-Expressionism · Artificial Realism
    'George Condo',
    # Neo-Expressionism · British Figuration
    'Cecily Brown',
    # Neo-Expressionism · Contemporary
    'Adrian Ghenie', 'Anselm Kiefer', 'David Wojnarowicz', 'Eddie Martinez',
    'Rita Ackermann', 'Robert Colescott', 'Robert Nava', 'Ross Bleckner',
    'Sigmar Polke', 'Zeng Fanzhi', 'Zhou Chunya',
    # Neo-Expressionism · Figurative Drawing
    'Robert Longo',
    # Neo-Expressionism · Postmodernism
    'David Salle',
    # Neo-Expressionism · Street Art
    'Aboudia', 'Jean-Michel Basquiat',
    # Neo-Expressionism · Transavanguardia
    'Sandro Chia',
    # New Media · Contemporary
    'Wang Yuyang',
    # Op Art · Modernism
    'Victor Vasarely',
    # Photography
    'Diane Arbus', 'Garry Winogrand', 'Henri Cartier-Bresson', 'Nan Goldin',
    'Philip-Lorca diCorcia', 'Robert Frank', 'Robert Mapplethorpe', 'William Eggleston',
    # Photography · Conceptual
    'Anne Collier',
    # Photography · Contemporary
    'Francesca Woodman', 'Peter Beard',
    # Photorealism
    'Richard Estes',
    # Photorealism · Contemporary
    'Chuck Close',
    # Pop Art · Ben-Day Dots · Comic Book
    'Roy Lichtenstein',
    # Pop Art · British Painting · Figuration
    'David Hockney',
    # Pop Art · California Realism
    'Wayne Thiebaud',
    # Pop Art · Seriality · Factory
    'Andy Warhol',
    # Pop Art · Street Art
    'Kenny Scharf',
    # Pop Art · West Coast · Language in Painting
    'Ed Ruscha',
    # Post-Impressionism
    'Henri de Toulouse-Lautrec', 'Pierre Bonnard',
    # Post-Impressionism · Fauvism
    'Albert Marquet',
    # Post-Impressionism · Impressionism
    'Johan Barthold Jongkind',
    # Post-Impressionism · Neo-Dada
    'Yves Klein',
    # Post-Impressionism · Neo-Impressionism
    'Henri-Edmond Cross',
    # Post-Minimalism · Contemporary
    'Lynda Benglis',
    # Pre-Impressionism · Marine Painting
    'Eugène Boudin',
    # Street Art · Contemporary
    'Futura 2000', 'Invader', 'José Parlá', 'Mehdi Ghadyanloo',
    # Street Art · Pop Art
    'Keith Haring',
    # Street Art · Post-Pop
    'KAWS',
})

_KNOWN_ARTISTS_LOWER: frozenset[str] = frozenset(k.lower() for k in KNOWN_ARTISTS)

# ── Hook templates ─────────────────────────────────────────────────────────────
# Each entry: (min_pct, [question variants], [answer variants])
# Format vars: {artist} {title} {house} {hammer} {estimate} {pct} {n}

_HOOK_TEMPLATES = [
    (800,
     [
         "nobody priced this right.",
         "the estimate was wrong by {pct}.",
         "the room ignored the catalogue.",
         "{house} said {estimate}. the room said {hammer}.",
         "what does {n} above estimate tell you?",
     ],
     [
         "a result this far above estimate isn't a market anomaly — it's the room rewriting the artist's place in the canon. "
         "what the catalogue priced as one thing, collectors recognized as something else entirely.",

         "estimates reflect what an artist has done. hammer prices reflect what collectors believe they will mean. "
         "at {n} above estimate, the room made a clear statement about {artist}'s legacy.",

         "'{title}' walked into that room as a catalogue entry. it left as a record. "
         "that's how art history gets repriced — not in museums, but at auction.",

         "the specialist's estimate is built on precedent. "
         "a {pct} overshoot means the room had already moved past that precedent — "
         "and recognized something in {artist}'s work that the catalogue hadn't caught up to.",
     ]),

    (500,
     [
         "the estimate was a suggestion.",
         "a {n} result doesn't happen by accident.",
         "the catalogue missed the room by {pct}.",
         "{house} set the floor at {estimate}. the bidders ignored it.",
         "what does it mean when the market pays {hammer} for a {estimate} estimate?",
     ],
     [
         "at this level, collectors aren't just buying a work — they're staking a position on the artist. "
         "the estimate reflects where {artist} has been. {hammer} is where the room thinks they're going.",

         "results like this happen when critical and market consensus finally align. "
         "a museum moment, a major publication, a retrospective — something shifted the conversation before this sale, and the room responded.",

         "provenance and period matter at this price. "
         "'{title}' carried a history the estimate didn't fully price — and the room understood what it was acquiring.",

         "a {pct} overshoot of this scale is a verdict on an artist's significance. "
         "the catalogue reflects the past record. the hammer is the new one.",
     ]),

    (300,
     [
         "the catalogue got this wrong by {pct}.",
         "the specialists underestimated the room.",
         "priced for safety. sold for ambition.",
         "from {estimate} to {hammer} — what changed?",
         "why does {artist} keep beating estimate?",
     ],
     [
         "auction rooms reprice artists faster than institutions do. "
         "{artist} had been estimated on old assumptions — the room corrected them.",

         "the estimate was set by precedent. the room was pricing on where {artist} now sits in the conversation — "
         "and that's a very different number.",

         "a result {pct} above estimate means someone arrived with deep knowledge of the work and the artist. "
         "that kind of conviction — anchored in research, not sentiment — is what moves an artist's market.",

         "the low estimate was {estimate}. it sold for {hammer}. "
         "that gap is enough to reset the artist's record, shift the reference point for every future valuation, and start a new chapter.",
     ]),

    (150,
     [
         "the room disagreed with the experts.",
         "the house priced it low. the room priced it right.",
         "conviction beat the catalogue.",
         "{estimate} estimate. {hammer} reality.",
         "why did this sell for {pct} above estimate?",
     ],
     [
         "the estimate is built from past sales. "
         "when the room bids {pct} above that, it's saying: the past doesn't tell the full story of this artist anymore.",

         "serious collectors don't bid on estimates — they bid on their own research. "
         "a {pct} overshoot usually means someone in that room understood {artist}'s significance better than the catalogue did.",

         "the auction house priced {artist} conservatively. "
         "the room disagreed — and when a room this competitive disagrees, the result becomes the new reference point.",

         "'{title}' is from a period in {artist}'s career that the market has been reassessing. "
         "the {pct} overshoot reflects that — a work carrying more weight than the estimate assumed.",
     ]),

    (80,
     [
         "the room knew something the catalogue didn't.",
         "more buyers arrived than the estimate assumed.",
         "the market priced what the house wouldn't.",
         "{pct} above estimate — is that a pattern or a fluke?",
         "the estimate was {estimate}. the hammer was {hammer}.",
     ],
     [
         "the estimate is a floor, not a forecast. "
         "when the room bids above it, it usually means the work carried more quality — or more significance — than the catalogue captured.",

         "{artist}'s presence in major collections and exhibitions has been building. "
         "a {pct} overshoot confirms the market has been paying attention.",

         "'{title}' outperformed because the room valued what it is, not just what {artist} has sold for before. "
         "the estimate anchors on history. the hammer reflects the present.",

         "when two serious collectors want the same work, the estimate becomes irrelevant. "
         "what matters is who understands the artist's importance — and who wants to own a piece of it.",
     ]),

    (40,
     [
         "priced to sell. sold for more.",
         "above estimate — the most common story in the room.",
         "the floor held. the ceiling didn't.",
         "from {estimate} to {hammer} — small gap, real signal.",
         "the room had more conviction than the catalogue.",
     ],
     [
         "a result above estimate — even modestly — confirms that demand for {artist}'s work is real and consistent. "
         "the catalogue sets the floor. the room decides the ceiling.",

         "the estimate reflects what specialists expected based on precedent. "
         "{hammer} is what collectors in that room were willing to pay — and that's always the more honest number.",

         "when a work sells above estimate, it's usually because the room found something in it the catalogue missed — "
         "quality, condition, period, or simply the right buyer at the right moment.",

         "a modest overshoot like this is quiet but meaningful. "
         "it tells you demand is ahead of where the specialists priced {artist}'s market.",
     ]),

    (0,
     [
         "above estimate — even here.",
         "the floor held. just.",
         "sold above the low estimate.",
         "{hammer} on a {estimate} estimate.",
         "even a small overshoot tells a story.",
     ],
     [
         "even a small overshoot confirms there was more than one serious buyer in the room. "
         "for {artist}, that demand matters — it keeps the market active and the next estimate honest.",

         "the estimate is a starting point. the hammer is the truth. "
         "here, the truth was just a little higher than the catalogue expected — and that's enough to move the conversation.",

         "a result above estimate — however modest — means the market for {artist} is healthy. "
         "collectors are paying attention, and competition, even at this level, is a signal worth reading.",

         "every lot that sells above estimate becomes part of an artist's price history. "
         "'{title}' just added one more data point — and it moved in the right direction.",
     ]),
]


# ── Helpers ────────────────────────────────────────────────────────────────────

def _fmt(usd: float) -> str:
    return f"${usd:,.0f}"

def _fmt_price_tts(usd: float) -> str:
    """Spoken-English price for TTS."""
    if usd >= 1_000_000:
        return f"{usd / 1_000_000:.1f} million dollars"
    if usd >= 1_000:
        return f"{usd / 1_000:.0f} thousand dollars"
    return f"{usd:.0f} dollars"

def _prices_to_speech(text: str) -> str:
    """Replace $X,XXX-style price tokens in arbitrary text with their spoken form."""
    def _sub(m: re.Match) -> str:
        digits = m.group(1).replace(",", "")
        return _fmt_price_tts(float(digits))
    return re.sub(r"\$([0-9][0-9,]*)", _sub, text)

def _pct_above(hammer: float, low: float) -> float:
    return round((hammer / low - 1) * 100, 1)

def _clean_artist(name: str) -> str:
    return re.sub(r"\s*\([^)]+\)\s*$", "", name or "").strip().title()

def _clean_house(raw: str) -> str:
    for key, label in [
        ("sotheby",  "Sotheby's"),
        ("christie", "Christie's"),
        ("phillips", "Phillips"),
        ("bonham",   "Bonhams"),
        ("ketterer", "Ketterer"),
        ("van ham",  "Van Ham"),
        ("grisebach","Grisebach"),
        ("lempertz", "Lempertz"),
    ]:
        if key in (raw or "").lower():
            return label
    return raw or "—"

def _strip_accents(s: str | None) -> str | None:
    if s is None:
        return None
    return "".join(c for c in unicodedata.normalize("NFD", s) if unicodedata.category(c) != "Mn")

def _week_bounds(ref_date: date) -> tuple[str, str]:
    monday = ref_date - timedelta(days=ref_date.weekday())
    return monday.isoformat(), (monday + timedelta(days=6)).isoformat()

def _make_slug(s: str, max_len: int = 30) -> str:
    s = _strip_accents(s) or s
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return s[:max_len].rstrip("-")

def _esc(s: str) -> str:
    """Escape a string for embedding in a Python dict literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


# ── Image preparation ──────────────────────────────────────────────────────────

def _download_image(url: str | None) -> Image.Image | None:
    if not url:
        return None
    try:
        r = httpx.get(url, timeout=20, follow_redirects=True,
                      headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                               "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"})
        r.raise_for_status()
        return Image.open(BytesIO(r.content)).convert("RGB")
    except Exception as e:
        print(f"  ⚠ download failed: {e}")
        return None

def _first_image_url(lot: dict) -> str | None:
    raw = lot.get("image_urls")
    if isinstance(raw, list):
        return raw[0] if raw else None
    if isinstance(raw, str):
        try:
            return json.loads(raw)[0]
        except (TypeError, ValueError, IndexError):
            return None
    return None

def _prepare_images(lot: dict, images_dir: Path) -> int:
    """
    Download artwork and write 4 reel images to images_dir:
      01_source.jpg — full source for Frame 1 (artist + title label)
      02_top.jpg    — square top-biased crop    (detail: head/subject)
      03_centre.jpg — square centre crop        (detail)
      04_source.jpg — full source again         (Frame 4 data reveal)

    Returns number of images written.
    """
    if images_dir.exists():
        shutil.rmtree(images_dir)
    images_dir.mkdir(parents=True, exist_ok=True)

    photo = _download_image(_first_image_url(lot))
    if not photo:
        return 0

    iw, ih = photo.size
    side   = min(iw, ih)
    cx     = (iw - side) // 2          # horizontal centre offset
    cy     = (ih - side) // 2          # vertical centre offset
    top_y  = max(0, (ih - side) // 6)  # slight top bias for face/subject

    photo.save(images_dir / "01_source.jpg", "JPEG", quality=95)
    photo.crop((cx, top_y, cx + side, top_y + side)).save(
        images_dir / "02_top.jpg", "JPEG", quality=95)
    photo.crop((cx, cy, cx + side, cy + side)).save(
        images_dir / "03_centre.jpg", "JPEG", quality=95)
    photo.save(images_dir / "04_source.jpg", "JPEG", quality=95)

    return 4


# ── Hook / caption ─────────────────────────────────────────────────────────────

def _hook_caption(lot: dict, pct: float) -> tuple[str, str]:
    """Return (question, answer) from the per-tier hook templates."""
    mult     = round(pct / 100 + 1, 1)
    artist   = _clean_artist(lot.get("artist") or "Unknown")
    title    = (lot.get("title") or "Untitled")[:40]
    house    = lot.get("auction_house") or "the auction house"
    hammer   = _fmt(lot["hammer_usd"])
    est_lo   = lot["estimate_low"]
    est_hi   = lot.get("estimate_high") or est_lo
    estimate = f"{_fmt(est_lo)}–{_fmt(est_hi)}"
    fmt = dict(n=f"{mult:.0f}×", artist=artist, title=title, house=house,
               hammer=hammer, estimate=estimate, pct=f"{pct:,.0f}%")
    for threshold, q_variants, a_variants in _HOOK_TEMPLATES:
        if pct >= threshold:
            return (random.choice(q_variants).format(**fmt),
                    random.choice(a_variants).format(**fmt))
    return "the hammer price tells the real story.", "follow the data."

def _social_captions(lot: dict) -> dict:
    pct       = _pct_above(lot["hammer_usd"], lot["estimate_low"])
    artist    = _clean_artist(lot.get("artist") or "Unknown")
    title     = lot.get("title") or "Untitled"
    house     = _clean_house(lot.get("auction_house") or "")
    est_lo    = lot["estimate_low"]
    est_hi    = lot.get("estimate_high") or est_lo
    sale_name = (lot.get("sale_name") or "").strip()
    url       = (lot.get("source_url") or "").strip()

    ig_parts = [
        f"{artist}\n",
        f'"{title}"\n\n',
        f"estimate: {_fmt(est_lo)}–{_fmt(est_hi)}\n",
        f"sold: {_fmt(lot['hammer_usd'])}  (+{pct:,.0f}% above estimate)\n\n",
        f"{sale_name}\n" if sale_name else "",
        f"{house}",
        f"\n{url}" if url else "",
        "\n\n#thehammerprice #artmarket #auctionresults",
    ]
    ig = "".join(ig_parts)
    tt_parts = [
        f"{artist} · \"{title}\"\n",
        f"estimate {_fmt(est_lo)}–{_fmt(est_hi)} → sold {_fmt(lot['hammer_usd'])} (+{pct:,.0f}%)\n",
        f"{sale_name} · " if sale_name else "",
        f"{house}",
        f"\n{url}" if url else "",
        "\n\n#thehammerprice #artmarket #auctionresults #artcollecting #foryou",
    ]
    tt = "".join(tt_parts)
    ln_parts = [
        f"{artist} — \"{title}\"\n\n",
        f"estimate: {_fmt(est_lo)}–{_fmt(est_hi)} | ",
        f"sold: {_fmt(lot['hammer_usd'])} (+{pct:,.0f}% above estimate)\n\n",
        f"{sale_name}\n" if sale_name else "",
        f"{house}",
        f"\n{url}" if url else "",
        f"\n\ndata source: {house}",
        "\n\n#thehammerprice #artmarket #auctionresults #artcollecting #contemporaryart",
    ]
    ln = "".join(ln_parts)
    return {"instagram": ig, "tiktok": tt, "linkedin": ln}


def _write_captions_md(output_dir: Path, lot: dict, captions: dict) -> None:
    """Write output/captions.md in the format post_to_buffer.py expects."""
    artist = _clean_artist(lot.get("artist") or "Unknown")
    title  = (lot.get("title") or "Untitled")[:60]
    ig     = captions.get("instagram", "")
    tt     = captions.get("tiktok", "")
    ln     = captions.get("linkedin", "")

    md = (
        f"*{artist} · \"{title}\"*\n\n"
        "## 📸 Instagram\n\n"
        "### Caption\n"
        f"```\n{ig}\n```\n\n"
        "## 🎵 TikTok\n\n"
        "### Caption\n"
        f"```\n{tt}\n```\n\n"
        "## 💼 LinkedIn\n\n"
        "### Caption\n"
        f"```\n{ln}\n```\n"
    )
    (output_dir / "captions.md").write_text(md, encoding="utf-8")


# ── Reel config ────────────────────────────────────────────────────────────────

def _generate_config(lot: dict, week_label: str, captions: dict,
                     frame_holds: list[float] | None = None,
                     narration_captions: list[dict] | None = None) -> str:
    """
    Write reel_config.py for make_reel.py.

    `frame_holds` (4 floats) overrides the default 5/2/2/8 pacing so the
    frames track the voiceover; `narration_captions` adds word-by-word
    caption cues (absolute video time) that make_reel.py overlays.

    Five frames (~19s total):
      Frame 1 (5s)  — full artwork, artist + title centred (no box)
      Frame 2 (2s)  — top crop detail (clean)
      Frame 3 (2s)  — left crop detail (clean)
      Frame 4 (2s)  — right crop detail (clean)
      Frame 5 (8s)  — centre crop, data reveal pushed to lower_third
    """
    artist    = _clean_artist(lot.get("artist") or "Unknown")
    title     = (lot.get("title") or "Untitled")[:50]
    hammer    = lot["hammer_usd"]
    est_lo    = lot["estimate_low"]
    est_hi    = lot.get("estimate_high") or est_lo
    pct       = _pct_above(hammer, est_lo)
    house     = lot.get("auction_house") or "Auction House"
    sale_name = (lot.get("sale_name") or "Contemporary Sale")[:40]
    scraped   = (lot.get("scraped_at") or "")[:10]
    year      = scraped[:4] if scraped else str(date.today().year)

    tag_line  = f"@thehammerprice  ·  {artist.lower()}  ·  {year}"
    est_str   = f"estimate: {_fmt(est_lo)}–{_fmt(est_hi)}"
    sold_str  = f"sold: {_fmt(hammer)}."
    pct_str   = f"+{pct:,.0f}% above estimate."

    caption_full = (
        f"the auction house said {_fmt(est_lo)}. the room said {_fmt(hammer)}. "
        f"{artist}'s {title} sold for +{pct:,.0f}% above the low estimate. "
        f"this is what happens when the data knows something the catalogue does not."
    )

    holds = frame_holds or [5.0, 2.0, 2.0, 8.0]

    per_frame = [
        # Frame 1 — full artwork, artist + title label (lower third)
        {
            "show_caption":     True,
            "caption_position": "lower_third",
            "tag":              tag_line,
            "line1":            artist,
            "line2":            title,
            "line3":            "",
            "hold_seconds":     round(holds[0], 1),
        },
        # Frame 2 — top crop detail (clean)
        {
            "show_caption":  False,
            "hold_seconds":  round(holds[1], 1),
        },
        # Frame 3 — centre crop detail (clean)
        {
            "show_caption":  False,
            "hold_seconds":  round(holds[2], 1),
        },
        # Frame 4 — full artwork again, data reveal (pushed low)
        {
            "show_caption":     True,
            "caption_position": "lower_third",
            "tag":              tag_line,
            "line1":            est_str,
            "line2":            sold_str,
            "line3":            pct_str,
            "hold_seconds":     round(holds[3], 1),
        },
    ]

    lines = [
        '"""',
        f"  REEL CONFIG — {artist} — {title[:30]}",
        f"  Week: {week_label}  ·  Generated by scripts/art_reel.py",
        '"""',
        "",
        "CONFIG = {",
        f'    "lot_id":         "{_esc(lot.get("id", ""))}",',
        "",
        "    # ── Caption lines (on-screen) ──────────────────────────",
        f'    "caption_tag":    "{_esc(tag_line)}",',
        f'    "caption_line1":  "{_esc(est_str)}",',
        f'    "caption_line2":  "{_esc(sold_str)}",',
        f'    "caption_line3":  "{_esc(pct_str)}",',
        "",
        "    # ── Location metadata ──────────────────────────────────",
        f'    "location_coords": "{_esc(house.upper())}",',
        f'    "location_name":   "{_esc(sale_name.upper())}",',
        f'    "location_season": "{_esc(year)}  ·  SALE RESULT",',
        '    "frame_label":     "@thehammerprice",',
        "",
        "    # ── Layout ────────────────────────────────────────────",
        '    "photo_fit_first":  True,',
        "",
        "    # ── Style ─────────────────────────────────────────────",
        '    "vibe":             "auction_editorial",',
        '    "caption_position": "lower_safe",',
        '    "bg_music":         True,',
        '    "transitions_enabled": False,',
        '    "block_reveal":       False,',
        '    "ken_burns":          True,',
        "",
        "    # ── Font overrides ─────────────────────────────────────",
        '    "fonts_override": {',
        '        "serif_lg":   ("InstrumentSerif-Regular.ttf", 82),',
        '        "serif_med":  ("InstrumentSerif-Regular.ttf",  58),',
        '        "italic_med": ("InstrumentSerif-Italic.ttf",  40),',
        '        "mono":       ("IBMPlexMono-Regular.ttf",      17),',
        '        "mono_sm":    ("IBMPlexMono-Regular.ttf",      14),',
        "    },",
        "",
        "    # ── Per-line colours ──────────────────────────────────",
        '    "color_line1": (210, 200, 178),',
        '    "color_line2": (201, 168, 76),',
        '    "color_line3": (230, 215, 175),',
        "",
        '    "caption_all_frames": False,',
        f'    "cover_hold_seconds": {COVER_HOLD_S},',
        "",
        "    # ── Pacing (19s total: 5+2+2+2+8) ──────────────────────",
        '    "fps":          5,',
        '    "hold_seconds": 0.0,',
        '    "fade_seconds": 0.8,',
        "",
        "    # ── Social captions ───────────────────────────────────",
        '    "topic":           "culture",',
        f'    "location":        "{_esc(house)}",',
        f'    "season":          "{_esc(year)}",',
        f'    "caption_full":    "{_esc(caption_full)}",',
        '    "caption_hero":    "they priced it wrong",',
        '    "personal_note":   "51% of lots at the major houses sell above estimate. '
        'that\'s not randomness — it\'s a pattern.",',
        f'    "engagement_hook": "{_esc(captions["instagram"][:120])}",',
        "",
        "    # ── Per-frame captions — 3 frames, ~20s ───────────────",
        '    "per_frame_captions": [',
    ]
    for fc in per_frame:
        lines.append("        {")
        for key, val in fc.items():
            lines.append(f"            {repr(key)}: {repr(val)},")
        lines.append("        },")
    lines.append("    ],")
    if narration_captions:
        lines.append("")
        lines.append("    # ── Word-by-word narration captions ───────────────────")
        lines.append('    "narration_captions": [')
        for cap in narration_captions:
            lines.append(f"        {{'start': {cap['start']:.2f}, "
                         f"'end': {cap['end']:.2f}, 'text': {cap['text']!r}}},")
        lines.append("    ],")
    lines.append("}")
    return "\n".join(lines) + "\n"


# ── Voiceover ──────────────────────────────────────────────────────────────────

def _build_voiceover(lot: dict, pct: float, reel_dir: Path) -> tuple[list | None, list | None]:
    """Generate voiceover.mp3 explaining the painting, plus spoken price data.

    Script: intro (frame 1) → 4-sentence painting explanation via
    ai_content.generate_hook_answer (frames 2–3) → price data (frame 4).
    make_reel.py picks up voiceover.mp3 and voiceover_timing.json from the
    reel folder automatically.

    Returns (frame_holds, narration_captions) scaled to the narration, or
    (None, None) when TTS is unavailable.
    """
    import reel_utils
    try:
        from ai_content import generate_hook_answer, generate_voiceover
    except Exception as e:
        print(f"  ⚠ Import error: {e} — skipping voice")
        return None, None

    artist = _clean_artist(lot.get("artist") or "Unknown")
    title  = (lot.get("title") or "untitled")[:80]
    est_lo = lot["estimate_low"]
    est_hi = lot.get("estimate_high") or est_lo

    lot_ctx = dict(lot)
    lot_ctx.update({
        "artist":       artist,
        "hammer_fmt":   _fmt(lot["hammer_usd"]),
        "estimate_fmt": f"{_fmt(est_lo)}–{_fmt(est_hi)}",
        "pct_above":    pct,
    })

    explanation = None
    try:
        explanation = generate_hook_answer(
            lot_ctx, f"why did {artist}'s work beat its estimate?")
        if explanation:
            print(f"  ✓ AI painting note: {explanation[:80]}...")
    except Exception as e:
        print(f"  ⚠ AI painting note error: {e}")
    if not explanation:
        explanation = (
            f"{artist.lower()} is one of the names the market keeps returning to. "
            f"when a work like this surfaces, the estimate is only a starting point."
        )
        print("  ▸ Painting note: using template")

    intro = f"this is {title.lower()}, by {artist.lower()}."
    data  = (
        f"the estimate was {_fmt_price_tts(est_lo)} to {_fmt_price_tts(est_hi)}. "
        f"it sold for {_fmt_price_tts(lot['hammer_usd'])}. "
        f"that's plus {pct:.0f} percent above estimate."
    )
    script = f"{intro}  {_prices_to_speech(explanation)}  {data}"

    vo_path = reel_dir / "voiceover.mp3"
    ok, word_timings = generate_voiceover(script, str(vo_path))
    if not ok:
        print("  ⚠ TTS unavailable — rendering without voiceover")
        return None, None

    word_timings = reel_utils.normalise_word_timings(word_timings)
    vo_dur = reel_utils.audio_duration(vo_path)
    if vo_dur <= 0 and word_timings:
        vo_dur = word_timings[-1]["end"] + 0.5
    if not word_timings:
        word_timings = reel_utils.evenly_spaced_words(script, vo_dur)

    # Section boundaries (seconds into the VO) from word counts
    n_intro = len(intro.split())
    n_expl  = len(_prices_to_speech(explanation).split())

    def _start_of(idx: int) -> float:
        return word_timings[idx]["start"] if idx < len(word_timings) else vo_dur

    t_expl = _start_of(n_intro)
    t_data = _start_of(n_intro + n_expl)

    # Frame holds: 1 = intro, 2+3 split the explanation, 4 = data + tail
    holds = [
        max(3.0, t_expl),
        max(2.0, (t_data - t_expl) / 2),
        max(2.0, (t_data - t_expl) / 2),
        max(6.0, vo_dur - t_data + 2.0),
    ]

    # VO starts after the cover; captions use absolute video time
    (reel_dir / "voiceover_timing.json").write_text(json.dumps({
        "audio_offset": COVER_HOLD_S,
        "word_timings": word_timings,
    }))
    narr_captions = reel_utils.words_to_captions(word_timings)
    for cap in narr_captions:
        cap["start"] += COVER_HOLD_S
        cap["end"]   += COVER_HOLD_S

    print(f"  ✓ Voiceover: {vo_dur:.1f}s, {len(word_timings)} words, "
          f"{len(narr_captions)} cues, holds "
          + "/".join(f"{h:.1f}" for h in holds))
    return holds, narr_captions


# ── Scoring ────────────────────────────────────────────────────────────────────

def _artist_is_notable(artist: str, notable_set: set[str] | None = None) -> bool:
    cleaned = _clean_artist(artist)
    if notable_set and cleaned in notable_set:
        return True
    cl = cleaned.lower()
    return any(k in cl or cl in k for k in _KNOWN_ARTISTS_LOWER)

def _score_lot(lot: dict, notable_set: set[str] | None = None) -> float:
    pct          = _pct_above(lot["hammer_usd"], lot["estimate_low"])
    hammer_usd   = lot["hammer_usd"] or 0
    pct_bonus    = math.log1p(max(pct, 0)) * 10
    hammer_bonus = math.log10(hammer_usd) * 5 if hammer_usd >= 100_000 else 0
    is_known     = _artist_is_notable(lot.get("artist") or "", notable_set)
    return pct_bonus + (is_known * 20) + (hammer_bonus * 0.75)


# ── DB helpers ─────────────────────────────────────────────────────────────────

def _open_db(path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.create_function("strip_accents", 1, _strip_accents)
    return conn

def _ensure_posted_table(conn: sqlite3.Connection) -> None:
    conn.execute("""
        CREATE TABLE IF NOT EXISTS posted_reels (
            lot_id      TEXT PRIMARY KEY,
            artist      TEXT,
            title       TEXT,
            hammer_usd  REAL,
            reel_slug   TEXT,
            platforms   TEXT,
            posted_at   TEXT DEFAULT (datetime('now'))
        )
    """)
    conn.commit()

def _posted_ids(conn: sqlite3.Connection) -> set[str]:
    return {r[0] for r in conn.execute("SELECT lot_id FROM posted_reels").fetchall()}

def _posted_count_for_artist(conn: sqlite3.Connection, artist: str) -> int:
    row = conn.execute(
        "SELECT COUNT(*) FROM posted_reels WHERE LOWER(artist) LIKE LOWER(?)",
        (f"%{artist}%",),
    ).fetchone()
    return row[0] if row else 0

def _record_posted(conn: sqlite3.Connection, lot: dict, slug: str,
                   platforms: list[str]) -> None:
    conn.execute("""
        INSERT OR REPLACE INTO posted_reels
            (lot_id, artist, title, hammer_usd, reel_slug, platforms)
        VALUES (?, ?, ?, ?, ?, ?)
    """, (lot["id"], lot.get("artist"), lot.get("title"),
          lot.get("hammer_usd"), slug, ",".join(platforms)))
    conn.commit()
    print(f"  ✓ recorded: {lot.get('artist')} — {(lot.get('title') or '')[:40]}")

def _like_clauses(artist: str | None, title: str | None) -> tuple[str, list]:
    parts, params = [], []
    if artist:
        parts.append("AND strip_accents(LOWER(artist)) LIKE strip_accents(LOWER(?))")
        params.append(f"%{artist}%")
    if title:
        parts.append("AND title LIKE ?")
        params.append(f"%{title}%")
    return " ".join(parts), params

def _query_lots(conn: sqlite3.Connection, limit: int = 50,
                exclude_ids: set | None = None,
                artist: str | None = None, title: str | None = None,
                week_start: str | None = None, week_end: str | None = None,
                order_by: str = "pct_above DESC") -> list[dict]:
    exclude      = tuple(exclude_ids or [])
    placeholders = ",".join("?" * len(exclude)) if exclude else "NULL"
    flt_sql, flt_params = _like_clauses(artist, title)
    date_sql    = "AND substr(scraped_at, 1, 10) BETWEEN ? AND ?" if week_start else ""
    date_params = (week_start, week_end) if week_start else ()
    rows = conn.execute(f"""
        SELECT id, artist, title, hammer_usd, estimate_low, estimate_high,
               sale_name, sale_date, scraped_at, auction_house, image_urls, source_url,
               ROUND((hammer_usd * 1.0 / estimate_low - 1) * 100, 1) AS pct_above
        FROM art_items
        WHERE sale_performance = 'above'
          AND hammer_usd IS NOT NULL
          AND estimate_low IS NOT NULL AND estimate_low > 0
          {date_sql}
          {flt_sql}
          {"AND id NOT IN (" + placeholders + ")" if exclude else ""}
        ORDER BY {order_by}
        LIMIT ?
    """, (*date_params, *flt_params, *exclude, limit)).fetchall()
    return [dict(r) for r in rows]

def _query_random_week_lot(conn: sqlite3.Connection,
                           exclude_ids: set | None = None,
                           artist: str | None = None) -> list[dict]:
    exclude      = tuple(exclude_ids or [])
    placeholders = ",".join("?" * len(exclude)) if exclude else "NULL"
    flt_sql, flt_params = _like_clauses(artist, None)
    rows = conn.execute(f"""
        SELECT id, artist, title, hammer_usd, estimate_low, estimate_high,
               sale_name, sale_date, scraped_at, auction_house, image_urls, source_url,
               ROUND((hammer_usd * 1.0 / estimate_low - 1) * 100, 1) AS pct_above,
               strftime('%Y-%W', scraped_at) AS week_key
        FROM art_items
        WHERE sale_performance = 'above'
          AND hammer_usd IS NOT NULL
          AND estimate_low IS NOT NULL AND estimate_low > 0
          {flt_sql}
          {"AND id NOT IN (" + placeholders + ")" if exclude else ""}
        GROUP BY week_key HAVING MAX(pct_above)
        ORDER BY RANDOM() LIMIT 1
    """, (*flt_params, *exclude)).fetchall()
    return [dict(r) for r in rows]

def _build_notable_artists_set(conn: sqlite3.Connection) -> set[str]:
    rows = conn.execute("""
        SELECT artist FROM art_items
        WHERE hammer_usd IS NOT NULL AND artist IS NOT NULL
        GROUP BY artist HAVING COUNT(*) >= 2 OR AVG(hammer_usd) > 50000
    """).fetchall()
    return {_clean_artist(r[0]) for r in rows if r[0]}

def _list_artists(conn: sqlite3.Connection) -> None:
    rows = conn.execute("""
        SELECT artist, COUNT(*) AS lots,
               ROUND(AVG(hammer_usd)) AS avg_hammer,
               ROUND(MAX(hammer_usd)) AS max_hammer,
               ROUND(AVG((hammer_usd * 1.0 / NULLIF(estimate_low, 0) - 1) * 100), 1) AS avg_pct
        FROM art_items
        WHERE hammer_usd IS NOT NULL AND artist IS NOT NULL
        GROUP BY artist ORDER BY lots DESC, avg_hammer DESC
    """).fetchall()
    if not rows:
        print("No artists found in database.")
        return
    print(f"\n{'#':<5} {'Artist':<40} {'Lots':>5} {'Avg $':>10} {'Max $':>10} {'Avg %+':>7}")
    print("─" * 80)
    for i, r in enumerate(rows, 1):
        name = _clean_artist(r["artist"] or "Unknown")
        avg  = f"${int(r['avg_hammer']):,}" if r["avg_hammer"] else "—"
        mx   = f"${int(r['max_hammer']):,}" if r["max_hammer"] else "—"
        pct  = f"+{r['avg_pct']:.1f}%"      if r["avg_pct"]    else "—"
        print(f"{i:<5} {name:<40} {r['lots']:>5} {avg:>10} {mx:>10} {pct:>7}")
    print(f"\n  {len(rows)} artists total. Use --artist \"<name>\" to filter.")


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a price-first auction reel (~20s)"
    )
    parser.add_argument("--list",         action="store_true", help="Preview top candidates without generating")
    parser.add_argument("--list-artists", action="store_true", help="List all artists in DB and exit")
    parser.add_argument("--all-time",     action="store_true", help="Best ever unposted (ignores week)")
    parser.add_argument("--week",         default=None,        help="ISO date in target week (default: today)")
    parser.add_argument("--artist",       default=None,        help="Filter by artist name (substring)")
    parser.add_argument("--title",        default=None,        help="Filter by title (substring)")
    parser.add_argument("--run",          action="store_true", help="Render video via make_reel.py after generating")
    parser.add_argument("--no-voice",     action="store_true", help="Skip the voiceover explaining the painting")
    args = parser.parse_args()

    if not DB_PATH.exists():
        print(f"✗ Database not found: {DB_PATH}")
        sys.exit(1)

    conn = _open_db(DB_PATH)
    _ensure_posted_table(conn)

    if args.list_artists:
        _list_artists(conn)
        conn.close()
        sys.exit(0)

    ref_date             = date.fromisoformat(args.week) if args.week else date.today()
    week_start, week_end = _week_bounds(ref_date)
    week_label           = f"{week_start} / {week_end}"
    order_by             = "hammer_usd DESC" if args.artist else "pct_above DESC"

    print("═" * 60)
    print("  ART REEL — The Hammer Price")
    print(f"  Mode: {'all-time' if args.all_time else f'week {week_label}'}")
    if args.artist:
        print(f"  Artist: \"{args.artist}\"")
    print("═" * 60)

    skip = _posted_ids(conn)
    if skip:
        print(f"\n  ℹ Skipping {len(skip)} already-posted lot(s).")

    # ── Query ──────────────────────────────────────────────────
    if args.all_time:
        lots = _query_lots(conn, 50, skip, args.artist, args.title, order_by=order_by)

        if not lots and args.artist:
            rotation = list(dict.fromkeys(_ca.get_rotation(DB_PATH)))
            try:
                start_idx = next(i for i, a in enumerate(rotation)
                                 if a.lower() == args.artist.lower())
            except StopIteration:
                start_idx = 0
            for offset in range(1, len(rotation)):
                next_artist = rotation[(start_idx + offset) % len(rotation)]
                if _posted_count_for_artist(conn, next_artist) >= _ca.MAX_LOTS_PER_ARTIST:
                    continue
                if _query_lots(conn, 1, skip, next_artist, order_by=order_by):
                    print(f"\n  ⚠ All {args.artist} lots posted — trying: {next_artist}")
                    lots = _query_lots(conn, 50, skip, next_artist, order_by=order_by)
                    break
            if not lots:
                print("\n  ⚠ No rotation candidate — falling back to unfiltered.")
                lots = _query_lots(conn, 50, skip, order_by=order_by)
    else:
        lots = _query_lots(conn, 50, skip, args.artist, args.title,
                           week_start, week_end, order_by)
        if not lots:
            rand = _query_random_week_lot(conn, skip, args.artist)
            if rand:
                ws, we = _week_bounds(date.fromisoformat(rand[0]["scraped_at"][:10]))
                print(f"  No data this week — using random week: {ws}")
                lots = _query_lots(conn, 50, skip, args.artist, args.title, ws, we, order_by)
        if not lots:
            print("  Falling back to all-time top unposted.")
            lots = _query_lots(conn, 50, skip, args.artist, args.title, order_by=order_by)

    # ── Score + pick ───────────────────────────────────────────
    notable = _build_notable_artists_set(conn)
    scored  = sorted(((l, _score_lot(l, notable)) for l in lots),
                     key=lambda x: x[1], reverse=True)

    if not scored:
        print("✗ No suitable lots found.")
        conn.close()
        sys.exit(1)

    lot    = scored[0][0]
    artist = _clean_artist(lot.get("artist") or "Unknown")
    pct    = _pct_above(lot["hammer_usd"], lot["estimate_low"])

    print(f"\n▸ {artist}")
    print(f"  {(lot.get('title') or 'Untitled')[:60]}")
    print(f"  estimate  {_fmt(lot['estimate_low'])}–{_fmt(lot.get('estimate_high') or lot['estimate_low'])}")
    print(f"  sold      {_fmt(lot['hammer_usd'])}  (+{pct:.0f}%)")
    print(f"  {lot.get('auction_house')}")

    if args.list:
        print(f"\n  {'#':<4} {'Artist':<30} {'Hammer':>12} {'%+':>7}  Score")
        print("  " + "─" * 60)
        for i, (l, score) in enumerate(scored[:5], 1):
            p = _pct_above(l["hammer_usd"], l["estimate_low"])
            print(f"  {i:<4} {_clean_artist(l.get('artist') or '')[:29]:<30} "
                  f"{_fmt(l['hammer_usd']):>12}  {p:>5.0f}%  {score:.0f}")
        conn.close()
        return

    # ── Build reel folder ──────────────────────────────────────
    artist_slug = _make_slug(artist)
    title_slug  = _make_slug(lot.get("title") or "untitled", max_len=20)
    reel_slug   = f"{ref_date.isoformat()}_{artist_slug}_{title_slug}"
    reel_dir    = REELS_DIR / reel_slug
    images_dir  = reel_dir / "images"
    output_dir  = reel_dir / "output"

    reel_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"\n▸ Reel folder: reels/{reel_slug}/")

    # ── Download + prepare images ──────────────────────────────
    print("\n▸ Preparing images...")
    n_images = _prepare_images(lot, images_dir)
    if n_images == 0:
        print("✗ No images downloaded — cannot generate reel.")
        conn.close()
        sys.exit(1)
    print(f"  ✓ {n_images} images (source + top/left/right detail + centre)")

    # ── Captions ───────────────────────────────────────────────
    captions = _social_captions(lot)
    _write_captions_md(output_dir, lot, captions)
    print(f"▸ Captions: reels/{reel_slug}/output/captions.md")

    # ── Voiceover (painting explanation) ───────────────────────
    frame_holds   = None
    narr_captions = None
    if not args.no_voice:
        print("\n▸ Generating voiceover...")
        frame_holds, narr_captions = _build_voiceover(lot, pct, reel_dir)

    # ── Write reel_config.py ───────────────────────────────────
    config_path = reel_dir / "reel_config.py"
    config_path.write_text(_generate_config(lot, week_label, captions,
                                            frame_holds=frame_holds,
                                            narration_captions=narr_captions))
    print(f"▸ Config: {config_path.relative_to(BUSINESS_DIR)}")

    # ── meta.json ──────────────────────────────────────────────
    meta = {
        "date":          ref_date.isoformat(),
        "slug":          reel_slug,
        "lot_id":        lot.get("id"),
        "artist":        artist,
        "title":         lot.get("title"),
        "auction_house": _clean_house(lot.get("auction_house") or ""),
        "hammer_usd":    lot.get("hammer_usd"),
        "estimate_low":  lot.get("estimate_low"),
        "estimate_high": lot.get("estimate_high"),
        "pct_above":     pct,
        "captions":      captions,
    }
    (reel_dir / "meta.json").write_text(json.dumps(meta, indent=2, ensure_ascii=False))

    # ── Record in posted_reels ─────────────────────────────────
    _record_posted(conn, lot, reel_slug, ["instagram", "tiktok"])
    conn.close()

    # ── Summary ────────────────────────────────────────────────
    print(f"\n✓ Ready → reels/{reel_slug}/")
    print(f"\n  Instagram caption:\n")
    print("  " + captions["instagram"].replace("\n", "\n  "))
    print(f"\n  To render:")
    print(f"    python reel_template/make_reel.py reels/{reel_slug}")

    # ── Optionally render ──────────────────────────────────────
    if args.run:
        print("\n▸ Running make_reel.py...")
        subprocess.run(
            [sys.executable, str(REEL_TEMPLATE / "make_reel.py"), str(reel_dir)],
            cwd=str(REEL_TEMPLATE.parent),
        )


if __name__ == "__main__":
    main()
