#!/usr/bin/env python3
"""
Post a reading quote reel to TikTok and Instagram via Buffer (Provenance account).

Uses the same Buffer credentials as the Hermès reel poster:
    PROVENANCE_BUFFER_TOKEN        — Buffer API access token
    PROVENANCE_BUFFER_TIKTOK_ID    — Buffer channel ID for Provenance TikTok
    PROVENANCE_BUFFER_INSTAGRAM_ID — Buffer channel ID for Provenance Instagram

Video is hosted via a GitHub release, same mechanism as other Provenance posts.

Usage:
    python scripts/post_quote_to_buffer.py reels/<quote-slug>
    python scripts/post_quote_to_buffer.py reels/<quote-slug> --schedule "2026-07-13T19:00:00+07:00"
    python scripts/post_quote_to_buffer.py reels/<quote-slug> --dry-run
    python scripts/post_quote_to_buffer.py reels/<quote-slug> --no-tiktok
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import httpx
from dotenv import load_dotenv

SCRIPT_DIR   = Path(__file__).resolve().parent
BUSINESS_DIR = SCRIPT_DIR.parent

load_dotenv(BUSINESS_DIR / ".env", override=False)

BUFFER_GRAPHQL = "https://api.buffer.com/graphql"
TOKEN          = os.getenv("PROVENANCE_BUFFER_TOKEN")
TT_CHANNEL     = os.getenv("PROVENANCE_BUFFER_TIKTOK_ID")
IG_CHANNEL     = os.getenv("PROVENANCE_BUFFER_INSTAGRAM_ID")

GITHUB_REPO = "alexsnowschool-business/alexsnowschool-business.github.io"

_HASHTAGS_TT = (
    "#reading #books #quotes #booktok #literature "
    " #foryou"
)
_HASHTAGS_IG = (
    "#reading #books #quotes #bookstagram #literature " )   


# ── Caption builder ───────────────────────────────────────────────────────────

def _build_captions(quote_text: str, author: str, book: str) -> dict[str, str]:
    attr = f"— {author}" if author else ""
    if book:
        attr += f", {book}"

    body = f'"{quote_text}"\n\n{attr}'.strip()

    tiktok = f"{body}\n\n{_HASHTAGS_TT}"
    instagram = f"{body}\n\n{_HASHTAGS_IG}"
    return {"tiktok": tiktok, "instagram": instagram}


# ── GitHub release upload ─────────────────────────────────────────────────────

def _upload_to_github(
    video_path: Path,
    cover_path: Path | None,
    reel_slug: str,
    dry_run: bool,
) -> str | None:
    tag    = reel_slug  # slug already starts with "quote-YYYY-MM-DD_..."
    assets = [str(video_path)]
    if cover_path and cover_path.exists():
        assets.append(str(cover_path))

    if dry_run:
        video_url = f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/{video_path.name}"
        print(f"  [dry-run] GitHub release tag: {tag}")
        print(f"  [dry-run] video URL: {video_url}")
        return video_url

    print(f"  Creating GitHub release '{tag}'...")
    result = subprocess.run(
        [
            "gh", "release", "create", tag,
            *assets,
            "--repo",  GITHUB_REPO,
            "--title", f"Quote — {reel_slug}",
            "--notes", "Auto-generated by quote reel pipeline",
        ],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        if "already exists" in result.stderr:
            print("  Release exists — uploading assets...")
            r2 = subprocess.run(
                ["gh", "release", "upload", tag, *assets,
                 "--repo", GITHUB_REPO, "--clobber"],
                capture_output=True, text=True,
            )
            if r2.returncode != 0:
                print(f"  ✗ Upload failed: {r2.stderr[:200]}")
                return None
        else:
            print(f"  ✗ GitHub release failed: {result.stderr[:200]}")
            return None

    video_url = f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/{video_path.name}"
    print(f"  ✓ {video_url}")
    return video_url


# ── Buffer GraphQL ────────────────────────────────────────────────────────────

_CREATE_POST = """
mutation CreatePost($input: CreatePostInput!) {
  createPost(input: $input) {
    ... on PostActionSuccess {
      post { id status dueAt }
    }
    ... on MutationError {
      message
    }
  }
}
"""


def _post_to_buffer(
    client:       httpx.Client,
    channel_id:   str,
    platform:     str,
    text:         str,
    video_url:    str,
    scheduled_at: str | None,
    dry_run:      bool,
) -> bool:
    if dry_run:
        print(f"  [dry-run] {platform}: channel={channel_id}")
        print(f"  Caption ({len(text)} chars): {text[:120]}...")
        return True

    metadata: dict = {}
    if platform == "TikTok":
        metadata["tiktok"] = {"title": text[:150]}
    elif platform == "Instagram":
        metadata["instagram"] = {"type": "reel", "shouldShareToFeed": True}

    variables: dict = {
        "input": {
            "channelId": channel_id,
            "text":      text,
            "assets":    [{"video": {"url": video_url}}],
            "metadata":  metadata,
        }
    }

    if scheduled_at:
        dt = datetime.fromisoformat(scheduled_at).astimezone(timezone.utc)
        variables["input"]["mode"]  = "customScheduled"
        variables["input"]["dueAt"] = dt.isoformat()
    else:
        variables["input"]["mode"] = "addToQueue"

    r = client.post(BUFFER_GRAPHQL, json={"query": _CREATE_POST, "variables": variables})

    if r.status_code != 200:
        print(f"  ✗ {platform} HTTP {r.status_code}: {r.text[:300]}")
        return False

    data   = r.json()
    errors = data.get("errors")
    if errors:
        print(f"  ✗ {platform} GraphQL error: {errors[0].get('message')}")
        return False

    result = data.get("data", {}).get("createPost", {})
    if "message" in result:
        print(f"  ✗ {platform} Buffer error: {result['message']}")
        return False

    post = result.get("post")
    if not post:
        print(f"  ✗ {platform} unexpected response: {json.dumps(data)[:400]}")
        return False

    print(f"  ✓ {platform} queued — id: {post['id']}  status: {post['status']}  due: {post.get('dueAt', 'queue')}")
    return True


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Post a reading quote reel to TikTok/Instagram via Buffer (Provenance)."
    )
    parser.add_argument("reel_dir",       help="Reel folder, e.g. reels/quote-2026-07-12_lemony-snicket-never-trus")
    parser.add_argument("--schedule",     default=None,
                        help="ISO 8601 datetime, e.g. 2026-07-13T19:00:00+07:00")
    parser.add_argument("--no-tiktok",    dest="tiktok",    action="store_false", default=True)
    parser.add_argument("--no-instagram", dest="instagram", action="store_false", default=True)
    parser.add_argument("--dry-run",      action="store_true")
    args = parser.parse_args()

    reel_dir  = BUSINESS_DIR / args.reel_dir
    reel_slug = reel_dir.name

    if not reel_dir.exists():
        print(f"✗ Reel folder not found: {reel_dir}")
        sys.exit(1)

    # Find the MP4 (named after the folder)
    video_path = reel_dir / f"{reel_slug}.mp4"
    if not video_path.exists():
        # fallback: any mp4 in the folder
        candidates = list(reel_dir.glob("*.mp4"))
        if not candidates:
            print(f"✗ No .mp4 found in {reel_dir}")
            sys.exit(1)
        video_path = candidates[0]

    cover_path = reel_dir / "frame.png"

    if not args.dry_run and not TOKEN:
        print("✗ PROVENANCE_BUFFER_TOKEN not set in .env")
        sys.exit(1)

    # Read quote metadata from a sidecar JSON if present, else parse from slug
    meta_path = reel_dir / "quote_meta.json"
    if meta_path.exists():
        meta = json.loads(meta_path.read_text())
        quote_text = meta.get("text", "")
        author     = meta.get("author", "")
        book       = meta.get("book", "")
    else:
        # Best-effort: extract from slug (author part only)
        quote_text = reel_slug.replace("-", " ")
        author     = ""
        book       = ""

    captions = _build_captions(quote_text, author, book)

    print("═" * 62)
    print("  BUFFER POSTER — Provenance Quote Reel")
    print(f"  Reel:    {reel_slug}")
    print(f"  Video:   {video_path.name}")
    print(f"  Mode:    {'DRY RUN' if args.dry_run else 'LIVE'}")
    if args.schedule:
        print(f"  Sched:   {args.schedule}")
    else:
        print(f"  Sched:   add to queue")
    print("═" * 62)

    # Step 1 — host on GitHub
    print("\n▸ Hosting video on GitHub releases...")
    video_url = _upload_to_github(video_path, cover_path, reel_slug, args.dry_run)
    if not video_url:
        sys.exit(1)

    # Step 2 — post to Buffer
    print("\n▸ Posting to Buffer...")
    headers = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
    results = []

    with httpx.Client(headers=headers, timeout=30) as client:
        if args.tiktok and (TT_CHANNEL or args.dry_run):
            ok = _post_to_buffer(
                client, TT_CHANNEL or "TT_ID", "TikTok",
                captions["tiktok"], video_url, args.schedule, args.dry_run,
            )
            results.append(("TikTok", ok))
        elif args.tiktok:
            print("  ⚠ PROVENANCE_BUFFER_TIKTOK_ID not set — skipping TikTok")

        if args.instagram and (IG_CHANNEL or args.dry_run):
            ok = _post_to_buffer(
                client, IG_CHANNEL or "IG_ID", "Instagram",
                captions["instagram"], video_url, args.schedule, args.dry_run,
            )
            results.append(("Instagram", ok))
        elif args.instagram and not IG_CHANNEL:
            print("  ⚠ PROVENANCE_BUFFER_INSTAGRAM_ID not set — skipping Instagram")

    print("\n" + "═" * 62)
    for platform, ok in results:
        print(f"  {'✓' if ok else '✗'} {platform}")
    if not results:
        print("  ⚠ No platforms posted — check channel IDs in .env")
    print("═" * 62)


if __name__ == "__main__":
    main()
