#!/usr/bin/env python3
"""
Post a generated reel to Instagram and TikTok via Buffer GraphQL API.

Buffer requires the video to be at a public URL — this script uploads the
MP4 to a GitHub release first, then passes that URL to Buffer.

Usage:
    python scripts/post_to_buffer.py reels/<slug>
    python scripts/post_to_buffer.py reels/<slug> --schedule "2026-05-24T19:00:00+07:00"
    python scripts/post_to_buffer.py reels/<slug> --dry-run

Requires in .env:
    BUFFER_TOKEN             — Buffer API access token
    BUFFER_INSTAGRAM_ID      — Buffer channel ID for Instagram
    BUFFER_TIKTOK_ID         — Buffer channel ID for TikTok (optional)
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import httpx
from dotenv import load_dotenv

# ── Paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR   = Path(__file__).resolve().parent
BUSINESS_DIR = SCRIPT_DIR.parent

load_dotenv(BUSINESS_DIR / ".env", override=False)  # env vars set by CI take precedence

BUFFER_GRAPHQL = "https://api.buffer.com/graphql"
TOKEN          = os.getenv("BUFFER_TOKEN")
IG_CHANNEL     = os.getenv("BUFFER_INSTAGRAM_ID")
TT_CHANNEL     = os.getenv("BUFFER_TIKTOK_ID")

GITHUB_REPO    = "alexsnowschool-business/alexsnowschool-business.github.io"


# ── Wikipedia art history blurb ───────────────────────────────────────────────

def _fetch_wiki_blurb(artist: str, title: str) -> str | None:
    """Return a 2–3 sentence art history blurb for the artist via Wikipedia."""
    wiki_headers = {"User-Agent": "thehammerprice-reel-bot/1.0 (https://github.com/alexsnowschool-business)"}
    try:
        with httpx.Client(timeout=10, headers=wiki_headers, follow_redirects=True) as client:
            # Step 1: search for the artist page
            search = client.get(
                "https://en.wikipedia.org/w/api.php",
                params={"action": "query", "list": "search", "srsearch": artist,
                        "format": "json", "srlimit": 1},
            )
            results = search.json().get("query", {}).get("search", [])
            if not results:
                return None

            page_title = results[0]["title"]

            # Step 2: fetch clean summary extract
            summary = client.get(
                f"https://en.wikipedia.org/api/rest_v1/page/summary/{page_title}"
            )
            extract = summary.json().get("extract", "")
            if not extract:
                return None

            # Take first 2–3 sentences, cap at 400 chars
            sentences = re.split(r'(?<=\.)\s+', extract.strip())
            blurb = ""
            for s in sentences[:3]:
                candidate = (blurb + " " + s).strip()
                if len(candidate) > 400:
                    break
                blurb = candidate

            if not blurb:
                return None

            return f"🎨 {blurb}\n\n📖 via Wikipedia"

    except Exception as e:
        print(f"  ⚠ Wikipedia lookup failed: {e}")
        return None


# ── Caption parser ─────────────────────────────────────────────────────────────

def _parse_captions(captions_md: str) -> dict[str, str]:
    """Extract caption text from the code block under each platform's ### Caption section."""
    def _extract(section_header: str) -> str:
        # Find the section, then grab the first ```...``` code block inside it
        pattern = rf"{re.escape(section_header)}.*?###\s+Caption\s+```(.*?)```"
        m = re.search(pattern, captions_md, re.DOTALL | re.IGNORECASE)
        return m.group(1).strip() if m else ""

    return {
        "instagram": _extract("## 📸 Instagram"),
        "tiktok":    _extract("## 🎵 TikTok"),
    }


# ── GitHub release upload ──────────────────────────────────────────────────────

def _upload_to_github(video_path: Path, reel_slug: str, dry_run: bool) -> str | None:
    """Upload MP4 to a GitHub release and return the public download URL."""
    tag = f"reel-{reel_slug}"

    if dry_run:
        url = f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/reel.mp4"
        print(f"  [dry-run] would upload to GitHub release: {tag}")
        print(f"  [dry-run] video URL: {url}")
        return url

    print(f"  Creating GitHub release '{tag}'...")
    result = subprocess.run(
        [
            "gh", "release", "create", tag,
            str(video_path),
            "--repo",  GITHUB_REPO,
            "--title", f"Reel {reel_slug}",
            "--notes", "Auto-generated by @thehammerprice reel pipeline",
        ],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        # Release may already exist — try uploading asset to existing release
        if "already exists" in result.stderr:
            print(f"  Release exists, uploading asset...")
            r2 = subprocess.run(
                ["gh", "release", "upload", tag, str(video_path),
                 "--repo", GITHUB_REPO, "--clobber"],
                capture_output=True, text=True,
            )
            if r2.returncode != 0:
                print(f"  ✗ GitHub upload failed: {r2.stderr[:200]}")
                return None
        else:
            print(f"  ✗ GitHub release failed: {result.stderr[:200]}")
            return None

    url = f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/reel.mp4"
    print(f"  ✓ Uploaded — {url}")
    return url


# ── Buffer GraphQL ─────────────────────────────────────────────────────────────

_CREATE_POST = """
mutation CreatePost($input: CreatePostInput!) {
  createPost(input: $input) {
    ... on PostActionSuccess {
      post {
        id
        status
        dueAt
      }
    }
  }
}
"""

def _post_to_buffer(
    client: httpx.Client,
    channel_id: str,
    platform: str,
    text: str,
    video_url: str,
    scheduled_at: str | None,
    dry_run: bool,
) -> bool:
    if dry_run:
        ts = scheduled_at or "queue"
        print(f"  [dry-run] {platform}: channel={channel_id}, schedule={ts}")
        print(f"  Caption: {text[:120]}...")
        return True

    # Platform-specific metadata
    metadata: dict = {}
    if platform == "Instagram":
        metadata["instagram"] = {"type": "reel", "shouldShareToFeed": True}
    elif platform == "TikTok":
        metadata["tiktok"] = {"title": text[:150]}

    variables: dict = {
        "input": {
            "channelId":      channel_id,
            "text":           text,
            "assets":         [{"video": {"url": video_url}}],
            "schedulingType": "free",
            "metadata":       metadata,
        }
    }


    if scheduled_at:
        dt = datetime.fromisoformat(scheduled_at).astimezone(timezone.utc)
        variables["input"]["mode"]  = "customScheduled"
        variables["input"]["dueAt"] = dt.isoformat()
    else:
        variables["input"]["mode"] = "addToQueue"

    r = client.post(
        BUFFER_GRAPHQL,
        json={"query": _CREATE_POST, "variables": variables},
    )

    if r.status_code != 200:
        print(f"  ✗ {platform} HTTP error: {r.status_code} — {r.text[:300]}")
        return False

    data = r.json()
    if data.get("errors"):
        print(f"  ✗ {platform} GraphQL error: {data['errors'][0].get('message')}")
        return False

    result = data.get("data", {}).get("createPost", {})
    if "message" in result:
        print(f"  ✗ {platform} error: {result['message']}")
        return False

    post = result.get("post", {})
    print(f"  ✓ {platform} queued — id: {post.get('id')}  status: {post.get('status')}  due: {post.get('dueAt', 'queue')}")
    return True


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Post a reel to Buffer")
    parser.add_argument("reel_dir",   help="Reel folder path relative to project root")
    parser.add_argument("--schedule", default=None,
                        help="ISO 8601 datetime to schedule, e.g. 2026-05-24T19:00:00+07:00")
    parser.add_argument("--no-instagram", dest="instagram", action="store_false", default=True)
    parser.add_argument("--no-tiktok",    dest="tiktok",    action="store_false", default=True)
    parser.add_argument("--dry-run",  action="store_true")
    args = parser.parse_args()

    reel_dir      = BUSINESS_DIR / args.reel_dir
    video_path    = reel_dir / "output" / "reel.mp4"
    captions_path = reel_dir / "output" / "captions.md"
    reel_slug     = reel_dir.name

    if not video_path.exists():
        print(f"✗ No reel.mp4 in {reel_dir / 'output'}")
        sys.exit(1)
    if not captions_path.exists():
        print(f"✗ No captions.md in {reel_dir / 'output'}")
        sys.exit(1)
    if not args.dry_run and not TOKEN:
        print("✗ BUFFER_TOKEN not set in .env")
        sys.exit(1)

    captions = _parse_captions(captions_path.read_text())

    # Parse artist + title from captions header line (*Artist · Year · Topic*)
    artist, title = "", ""
    header_m = re.search(r'^\*(.+?)\s+·', captions_path.read_text(), re.MULTILINE)
    if header_m:
        artist = header_m.group(1).strip()
    # Also try reel_config.py if present
    house, hammer_fmt = "", ""
    config_path = reel_dir / "reel_config.py"
    if config_path.exists():
        cfg_text = config_path.read_text()
        am = re.search(r"'upper_artist'\s*:\s*'([^']+)'", cfg_text)
        tm = re.search(r"'upper_title'\s*:\s*'([^']+)'", cfg_text)
        hm = re.search(r'"location"\s*:\s*"([^"]+)"', cfg_text)
        fm = re.search(r'"caption_line2"\s*:\s*"([^"]+)"', cfg_text)
        if am: artist     = am.group(1)
        if tm: title      = tm.group(1)
        if hm: house      = hm.group(1)
        if fm: hammer_fmt = fm.group(1).replace("sold: ", "").rstrip(".")

    print("═" * 60)
    print("  BUFFER POSTER — The Hammer Price")
    print(f"  Reel:  {reel_slug}")
    print(f"  Mode:  {'DRY RUN' if args.dry_run else 'LIVE'}")
    if args.schedule:
        print(f"  Sched: {args.schedule}")
    else:
        print(f"  Sched: add to queue")
    print("═" * 60)

    # Fetch art history blurb for Instagram first comment
    # Prefer AI (OpenRouter) if key is set, fall back to Wikipedia
    first_comment = None
    if artist:
        ai_key = os.getenv("OPENROUTER_API_KEY")
        if ai_key:
            print(f"\n▸ Generating art history for '{artist}' via OpenRouter...")
            try:
                sys.path.insert(0, str(SCRIPT_DIR))
                from ai_content import generate_art_history
                lot_data = {"artist": artist, "title": title,
                            "auction_house": house, "hammer_fmt": hammer_fmt}
                first_comment = generate_art_history(lot_data)
                if first_comment:
                    print(f"  ✓ AI blurb: {first_comment[:80]}...")
                else:
                    print("  ⚠ AI generation failed — falling back to Wikipedia")
            except Exception as e:
                print(f"  ⚠ AI error: {e} — falling back to Wikipedia")

        if not first_comment:
            print(f"\n▸ Fetching art history for '{artist}' via Wikipedia...")
            first_comment = _fetch_wiki_blurb(artist, title)
            if first_comment:
                print(f"  ✓ Wikipedia blurb: {first_comment[:80]}...")
            else:
                print(f"  ⚠ No entry found — skipping first comment")

    # Step 1 — host the video on GitHub
    print("\n▸ Hosting video on GitHub releases...")
    video_url = _upload_to_github(video_path, reel_slug, args.dry_run)
    if not video_url:
        sys.exit(1)

    # Step 2 — post to Buffer
    print("\n▸ Posting to Buffer...")
    headers = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
    results = []

    with httpx.Client(headers=headers, timeout=30) as client:
        if args.instagram and (IG_CHANNEL or args.dry_run):
            ok = _post_to_buffer(client, IG_CHANNEL or "IG_ID", "Instagram",
                                 captions["instagram"], video_url, args.schedule,
                                 args.dry_run)
            results.append(("Instagram", ok))
        elif args.instagram:
            print("  ⚠ BUFFER_INSTAGRAM_ID not set — skipping")

        if args.tiktok and (TT_CHANNEL or args.dry_run):
            ok = _post_to_buffer(client, TT_CHANNEL or "TT_ID", "TikTok",
                                 captions["tiktok"], video_url, args.schedule, args.dry_run)
            results.append(("TikTok", ok))
        elif args.tiktok and not TT_CHANNEL:
            print("  ⚠ BUFFER_TIKTOK_ID not set — skipping")

    print("\n" + "═" * 60)
    for platform, ok in results:
        print(f"  {'✓' if ok else '✗'} {platform}")
    print("═" * 60)

    # Record successful post to avoid duplication in future runs
    posted_platforms = [p for p, ok in results if ok]
    if posted_platforms and not args.dry_run:
        lot_id = None
        config_path = reel_dir / "reel_config.py"
        if config_path.exists():
            id_m = re.search(r'"lot_id"\s*:\s*"([^"]+)"', config_path.read_text())
            if id_m: lot_id = id_m.group(1)
        if lot_id:
            import sqlite3
            db_path = BUSINESS_DIR / "data" / "art.db"
            if db_path.exists():
                conn = sqlite3.connect(db_path)
                conn.execute("""
                    INSERT OR REPLACE INTO posted_reels
                        (lot_id, artist, title, hammer_usd, reel_slug, platforms)
                    VALUES (?, ?, ?, ?, ?, ?)
                """, (lot_id, artist, title, None, reel_slug, ",".join(posted_platforms)))
                conn.commit()
                conn.close()
                print(f"  ✓ Recorded in posted_reels (lot_id={lot_id})")


if __name__ == "__main__":
    main()
