#!/usr/bin/env python3
"""
Post an artist story card carousel to Instagram via Buffer GraphQL.

Usage:
    python scripts/post_artist_cards_to_buffer.py output/artist_cards/<slug>
    python scripts/post_artist_cards_to_buffer.py output/artist_cards/<slug> --dry-run
    python scripts/post_artist_cards_to_buffer.py output/artist_cards/<slug> --schedule "2026-07-18T19:00:00+07:00"

Requires in environment:
    BUFFER_TOKEN          — Buffer API access token
    BUFFER_INSTAGRAM_ID   — Buffer channel ID for Instagram
    BUFFER_TIKTOK_ID      — Buffer channel ID for TikTok (optional)
"""

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import httpx
from dotenv import load_dotenv

SCRIPT_DIR   = Path(__file__).resolve().parent
BUSINESS_DIR = SCRIPT_DIR.parent

load_dotenv(BUSINESS_DIR / ".env", override=False)

BUFFER_GRAPHQL = "https://api.buffer.com/graphql"
GITHUB_REPO    = "alexsnowschool-business/alexsnowschool-business.github.io"

TOKEN      = os.getenv("BUFFER_TOKEN")
IG_CHANNEL = os.getenv("BUFFER_INSTAGRAM_ID")
TT_CHANNEL = os.getenv("BUFFER_TIKTOK_ID")

_HASHTAGS_IG = "#arthistory  #artlovers #thehammerprice"
_HASHTAGS_TT = "#arthistory #artlovers #fineart #artoftheday #thehammerprice"

_CREATE_POST = """
mutation CreatePost($input: CreatePostInput!) {
  createPost(input: $input) {
    ... on PostActionSuccess {
      post { id status dueAt }
    }
    ... on MutationError {
      message
    }
  }
}
"""


def _build_caption(meta: dict, hashtags: str) -> str:
    profile  = meta.get("profile", {})
    name     = profile.get("full_name") or meta.get("artist_name", "")
    movement = profile.get("art_movement", "")
    quote    = profile.get("quote", "")

    lines = [f"{name}" + (f"  ·  {movement}" if movement else "")]
    if quote:
        lines.append(f'\n"{quote}"')
    lines.append("\nSwipe to explore a life in art →")
    lines.append(f"\n{hashtags}")

    return "\n".join(lines).strip()


def _upload_images_to_github(image_paths: list[Path], slug: str, dry_run: bool) -> list[str] | None:
    tag = f"artist-cards-{slug}-{int(time.time())}"

    if dry_run:
        urls = [f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/{p.name}" for p in image_paths]
        print(f"  [dry-run] would upload {len(image_paths)} images to GitHub release: {tag}")
        return urls

    print(f"  Creating GitHub release '{tag}'...")
    result = subprocess.run(
        [
            "gh", "release", "create", tag,
            *[str(p) for p in image_paths],
            "--repo",  GITHUB_REPO,
            "--title", f"Artist Cards — {slug}",
            "--notes", "Auto-generated by artist_story_cards.py",
        ],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        print(f"  ✗ GitHub release failed: {result.stderr[:200]}")
        return None

    urls = [f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/{p.name}" for p in image_paths]
    print(f"  ✓ Uploaded {len(urls)} images")
    return urls


def _post_carousel(
    client: httpx.Client,
    channel_id: str,
    platform: str,
    text: str,
    image_urls: list[str],
    scheduled_at: str | None,
    dry_run: bool,
) -> bool:
    if dry_run:
        print(f"  [dry-run] {platform}: channel={channel_id}, images={len(image_urls)}, schedule={scheduled_at or 'queue'}")
        print(f"  Caption: {text[:120]}...")
        return True

    metadata: dict = {}
    if platform == "Instagram":
        metadata["instagram"] = {"type": "post", "shouldShareToFeed": True}
    elif platform == "TikTok":
        metadata["tiktok"] = {}

    variables: dict = {
        "input": {
            "channelId":      channel_id,
            "text":           text,
            "assets":         [{"image": {"url": url}} for url in image_urls],
            "schedulingType": "automatic",
            "metadata":       metadata,
        }
    }

    if scheduled_at:
        dt = datetime.fromisoformat(scheduled_at).astimezone(timezone.utc)
        variables["input"]["mode"]  = "customScheduled"
        variables["input"]["dueAt"] = dt.isoformat()
    else:
        variables["input"]["mode"] = "addToQueue"

    r = client.post(BUFFER_GRAPHQL, json={"query": _CREATE_POST, "variables": variables})

    if r.status_code != 200:
        print(f"  ✗ {platform} HTTP {r.status_code}: {r.text[:300]}")
        return False

    data = r.json()
    if data.get("errors"):
        print(f"  ✗ {platform} GraphQL error: {data['errors'][0].get('message')}")
        return False

    result = data.get("data", {}).get("createPost", {})
    if "message" in result:
        print(f"  ✗ {platform} Buffer error: {result['message']}")
        print(f"      Full response: {json.dumps(data)[:400]}")
        return False

    post = result.get("post")
    if not post:
        print(f"  ✗ {platform} unexpected response: {json.dumps(data)[:400]}")
        return False

    print(f"  ✓ {platform} queued — id: {post['id']}  status: {post['status']}  due: {post.get('dueAt', 'queue')}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Post artist story cards carousel to Buffer.")
    parser.add_argument("cards_dir", help="Folder from artist_story_cards.py, e.g. output/artist_cards/artist-2026-07-18-dali")
    parser.add_argument("--schedule", default=None, help="ISO 8601 datetime, e.g. 2026-07-18T19:00:00+07:00")
    parser.add_argument("--no-instagram", dest="instagram", action="store_false", default=True)
    parser.add_argument("--no-tiktok",    dest="tiktok",    action="store_false", default=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    cards_dir = BUSINESS_DIR / args.cards_dir
    meta_path = cards_dir / "meta.json"

    if not cards_dir.is_dir():
        print(f"✗ Folder not found: {cards_dir}")
        sys.exit(1)
    if not meta_path.exists():
        print(f"✗ No meta.json in {cards_dir}")
        sys.exit(1)
    if not args.dry_run and not TOKEN:
        print("✗ BUFFER_TOKEN not set in environment")
        sys.exit(1)
    if not args.dry_run and args.instagram and not IG_CHANNEL:
        print("✗ BUFFER_INSTAGRAM_ID not set in environment")
        sys.exit(1)

    meta   = json.loads(meta_path.read_text())
    images = sorted(cards_dir.glob("*.png"))
    if not images:
        print(f"✗ No PNG cards found in {cards_dir}")
        sys.exit(1)

    caption_ig = _build_caption(meta, _HASHTAGS_IG)
    caption_tt = _build_caption(meta, _HASHTAGS_TT)
    artist     = meta.get("profile", {}).get("full_name") or meta.get("artist_name", cards_dir.name)

    print("═" * 60)
    print("  BUFFER POSTER — Artist Story Cards")
    print(f"  Artist: {artist}")
    print(f"  Folder: {cards_dir.name}")
    print(f"  Cards:  {len(images)}")
    print(f"  Mode:   {'DRY RUN' if args.dry_run else 'LIVE'}")
    if args.schedule:
        print(f"  Sched:  {args.schedule}")
    print("═" * 60)

    print("\n▸ Hosting images on GitHub releases...")
    image_urls = _upload_images_to_github(images, cards_dir.name, args.dry_run)
    if not image_urls:
        sys.exit(1)

    print("\n▸ Posting to Buffer...")
    headers = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
    results = []

    with httpx.Client(headers=headers, timeout=30) as client:
        if args.instagram and (IG_CHANNEL or args.dry_run):
            ok = _post_carousel(client, IG_CHANNEL or "IG_ID", "Instagram",
                                caption_ig, image_urls, args.schedule, args.dry_run)
            results.append(("Instagram", ok))
        elif args.instagram:
            print("  ⚠ BUFFER_INSTAGRAM_ID not set — skipping")

        if args.tiktok and (TT_CHANNEL or args.dry_run):
            ok = _post_carousel(client, TT_CHANNEL or "TT_ID", "TikTok",
                                caption_tt, image_urls, args.schedule, args.dry_run)
            results.append(("TikTok", ok))
        elif args.tiktok and not TT_CHANNEL:
            print("  ⚠ BUFFER_TIKTOK_ID not set — skipping")

    print("\n" + "═" * 60)
    for platform, ok in results:
        print(f"  {'✓' if ok else '✗'} {platform}")
    print("═" * 60)


if __name__ == "__main__":
    main()
