#!/usr/bin/env python3
"""
Post a 5-quote card carousel to Instagram via Buffer GraphQL — a carousel of
still images, not a video. TikTok is intentionally not supported here: photo
carousel posts have had unresolved issues on TikTok's side in this codebase
(see post_beat_the_estimate_to_buffer.py) — video reels stay TikTok's format.

Usage:
    python scripts/post_quote_cards_to_buffer.py output/quote_cards/<slug> --dry-run
    python scripts/post_quote_cards_to_buffer.py output/quote_cards/<slug>
    python scripts/post_quote_cards_to_buffer.py output/quote_cards/<slug> --schedule "2026-07-15T19:00:00+07:00"
"""

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import httpx
from dotenv import load_dotenv

SCRIPT_DIR   = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
BUSINESS_DIR = SCRIPT_DIR.parent

load_dotenv(BUSINESS_DIR / ".env", override=False)

BUFFER_GRAPHQL = "https://api.buffer.com/graphql"
GITHUB_REPO    = "alexsnowschool-business/alexsnowschool-business.github.io"


def _build_caption(quotes: list[dict], hashtags: str) -> str:
    first = quotes[0]
    attr  = f"— {first['author']}" if first["author"] else ""
    if first.get("book"):
        attr += f", {first['book']}"

    body = f'"{first["text"]}"\n\n{attr}'.strip()
    body += f"\n\nSwipe for {len(quotes) - 1} more →" if len(quotes) > 1 else ""

    return f"{body}\n\n{hashtags}".strip()


def _upload_images_to_github(image_paths: list[Path], slug: str, dry_run: bool) -> list[str] | None:
    # Unique tag per invocation (not just per day) — same fix as
    # post_beat_the_estimate_to_buffer.py: `gh release upload --clobber`
    # deletes-then-reuploads, so a shared tag risks a race with an
    # in-flight Buffer image fetch from a previous run.
    tag = f"quote-cards-{slug}-{int(time.time())}"

    if dry_run:
        urls = [f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/{p.name}" for p in image_paths]
        print(f"  [dry-run] would upload {len(image_paths)} images to GitHub release: {tag}")
        return urls

    print(f"  Creating GitHub release '{tag}'...")
    result = subprocess.run(
        [
            "gh", "release", "create", tag,
            *[str(p) for p in image_paths],
            "--repo",  GITHUB_REPO,
            "--title", f"Quote Cards — {slug}",
            "--notes", "Auto-generated by quote_cards.py",
        ],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        print(f"  ✗ GitHub release failed: {result.stderr[:200]}")
        return None

    urls = [f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/{p.name}" for p in image_paths]
    print(f"  ✓ Uploaded {len(urls)} images")
    return urls


_CREATE_POST = """
mutation CreatePost($input: CreatePostInput!) {
  createPost(input: $input) {
    ... on PostActionSuccess {
      post { id status dueAt }
    }
    ... on MutationError {
      message
    }
  }
}
"""


def _post_to_buffer(
    client: httpx.Client,
    channel_id: str,
    text: str,
    image_urls: list[str],
    scheduled_at: str | None,
    dry_run: bool,
) -> bool:
    if dry_run:
        print(f"  [dry-run] Instagram: channel={channel_id}, images={len(image_urls)}, schedule={scheduled_at or 'queue'}")
        print(f"  Caption: {text[:120]}...")
        return True

    # Instagram's `type` only accepts post/story/reel — a multi-image
    # carousel is just a "post" with multiple image assets; Buffer infers
    # the carousel from the asset count (confirmed in beat_the_estimate poster).
    variables: dict = {
        "input": {
            "channelId":      channel_id,
            "text":           text,
            "assets":         [{"image": {"url": url}} for url in image_urls],
            "schedulingType": "automatic",
            "metadata":       {"instagram": {"type": "post", "shouldShareToFeed": True}},
        }
    }

    if scheduled_at:
        dt = datetime.fromisoformat(scheduled_at).astimezone(timezone.utc)
        variables["input"]["mode"]  = "customScheduled"
        variables["input"]["dueAt"] = dt.isoformat()
    else:
        variables["input"]["mode"] = "addToQueue"

    r = client.post(BUFFER_GRAPHQL, json={"query": _CREATE_POST, "variables": variables})

    if r.status_code != 200:
        print(f"  ✗ Instagram HTTP {r.status_code}: {r.text[:300]}")
        return False

    data = r.json()
    if data.get("errors"):
        print(f"  ✗ Instagram GraphQL error: {data['errors'][0].get('message')}")
        return False

    result = data.get("data", {}).get("createPost", {})
    if "message" in result:
        print(f"  ✗ Instagram Buffer error: {result['message']}")
        return False

    post = result.get("post")
    if not post:
        print(f"  ✗ Instagram unexpected response: {json.dumps(data)[:400]}")
        return False

    print(f"  ✓ Instagram queued — id: {post['id']}  status: {post['status']}  due: {post.get('dueAt', 'queue')}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Post a quote card carousel to Instagram via Buffer.")
    parser.add_argument("cards_dir",  help="Folder from quote_cards.py, e.g. output/quote_cards/cards-2026-07-15_slug")
    parser.add_argument("--account",  default="lifequoteshere",
                        help="Account slug matching accounts/<slug>.yaml")
    parser.add_argument("--schedule", default=None, help="ISO 8601 datetime, e.g. 2026-07-15T19:00:00+07:00")
    parser.add_argument("--dry-run",  action="store_true")
    args = parser.parse_args()

    import account_config
    try:
        cfg = account_config.load(args.account)
    except FileNotFoundError as e:
        print(f"✗ {e}")
        sys.exit(1)

    TOKEN      = os.getenv(cfg.get("buffer_token_env",        "PROVENANCE_BUFFER_TOKEN"))
    IG_CHANNEL = os.getenv(cfg.get("buffer_instagram_id_env", "PROVENANCE_BUFFER_INSTAGRAM_ID"))
    hashtags   = cfg.get("hashtags_instagram", "")

    cards_dir = BUSINESS_DIR / args.cards_dir
    meta_path = cards_dir / "meta.json"

    if not cards_dir.is_dir():
        print(f"✗ Folder not found: {cards_dir}")
        sys.exit(1)
    if not meta_path.exists():
        print(f"✗ No meta.json in {cards_dir} — did quote_cards.py generate this folder?")
        sys.exit(1)

    token_env = cfg.get("buffer_token_env", "PROVENANCE_BUFFER_TOKEN")
    if not args.dry_run and not TOKEN:
        print(f"✗ {token_env} not set in environment")
        sys.exit(1)
    if not args.dry_run and not IG_CHANNEL:
        print(f"✗ {cfg.get('buffer_instagram_id_env', 'PROVENANCE_BUFFER_INSTAGRAM_ID')} not set in environment")
        sys.exit(1)

    meta   = json.loads(meta_path.read_text())
    quotes = meta.get("quotes", [])
    images = sorted(cards_dir.glob("*.png"))
    if not images:
        print(f"✗ No PNG cards found in {cards_dir}")
        sys.exit(1)
    if not quotes:
        print(f"✗ No quotes in meta.json")
        sys.exit(1)

    print("═" * 60)
    print("  BUFFER POSTER — Quote Cards (carousel)")
    print(f"  Folder: {cards_dir.name}")
    print(f"  Cards:  {len(images)}")
    print(f"  Mode:   {'DRY RUN' if args.dry_run else 'LIVE'}")
    print("═" * 60)

    caption = _build_caption(quotes, hashtags)

    print("\n▸ Hosting images on GitHub releases...")
    image_urls = _upload_images_to_github(images, cards_dir.name, args.dry_run)
    if not image_urls:
        sys.exit(1)

    print("\n▸ Posting to Buffer...")
    headers = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}

    with httpx.Client(headers=headers, timeout=30) as client:
        ok = _post_to_buffer(client, IG_CHANNEL or "IG_ID", caption, image_urls, args.schedule, args.dry_run)

    print("\n" + "═" * 60)
    print(f"  {'✓' if ok else '✗'} Instagram")
    print("═" * 60)


if __name__ == "__main__":
    main()
