#!/usr/bin/env python3
"""
Post a Provenance Hermès reel to TikTok (and optionally Instagram) via Buffer.

Uses separate Buffer credentials from the @thehammerprice account — add these
to your .env:
    PROVENANCE_BUFFER_TOKEN        — Buffer API access token for Provenance
    PROVENANCE_BUFFER_TIKTOK_ID    — Buffer channel ID for Provenance TikTok
    PROVENANCE_BUFFER_INSTAGRAM_ID — Buffer channel ID for Provenance Instagram (optional)

Video is hosted via a GitHub release (same mechanism as post_to_buffer.py).

Usage:
    python scripts/post_to_buffer_provenance.py reels/<slug>
    python scripts/post_to_buffer_provenance.py reels/<slug> --schedule "2026-06-01T19:00:00+07:00"
    python scripts/post_to_buffer_provenance.py reels/<slug> --dry-run
    python scripts/post_to_buffer_provenance.py reels/<slug> --no-instagram
"""

import argparse
import importlib.util
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import httpx
from dotenv import load_dotenv

SCRIPT_DIR   = Path(__file__).resolve().parent
BUSINESS_DIR = SCRIPT_DIR.parent

load_dotenv(BUSINESS_DIR / ".env", override=False)

BUFFER_GRAPHQL = "https://api.buffer.com/graphql"
TOKEN          = os.getenv("PROVENANCE_BUFFER_TOKEN")
TT_CHANNEL     = os.getenv("PROVENANCE_BUFFER_TIKTOK_ID")
IG_CHANNEL     = os.getenv("PROVENANCE_BUFFER_INSTAGRAM_ID")

GITHUB_REPO    = "alexsnowschool-business/alexsnowschool-business.github.io"

_HASHTAGS_TT = (
    "#hermès #hermesbirkin "
    "#provenance #hermeskelly #resellluxury"
)
_HASHTAGS_IG = (
    "#hermès #provenance #luxurybags"
)


# ── Caption builder ────────────────────────────────────────────────────────────

def _load_config(reel_dir: Path) -> dict:
    """Load CONFIG dict from reel_config.py."""
    config_path = reel_dir / "reel_config.py"
    if not config_path.exists():
        return {}
    spec = importlib.util.spec_from_file_location("reel_config", config_path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return dict(mod.CONFIG)


def _build_captions(cfg: dict, captions_md: Path) -> dict[str, str]:
    """
    Return {tiktok, instagram} captions.
    Prefers captions.md if it exists; falls back to reel_config.py fields.
    """
    if captions_md.exists():
        text = captions_md.read_text()

        def _extract(header: str) -> str:
            m = re.search(
                rf"{re.escape(header)}.*?###\s+Caption\s+```(.*?)```",
                text, re.DOTALL | re.IGNORECASE,
            )
            return m.group(1).strip() if m else ""

        tt = _extract("## 🎵 TikTok")
        ig = _extract("## 📸 Instagram")
        if tt or ig:
            return {"tiktok": tt, "instagram": ig}

    # Build from reel_config fields
    caption_full    = cfg.get("caption_full", "")
    engagement_hook = cfg.get("engagement_hook", "")
    caption_hero    = cfg.get("caption_hero", "")
    line3           = cfg.get("caption_line3", "")   # e.g. "+245% above retail"
    location_name   = cfg.get("location_name", "")  # e.g. "KELLY 25"

    # TikTok: tight hook + data + hashtags (≤ 2 200 chars)
    tiktok = (
        f"{caption_hero}\n\n"
        f"{caption_full}\n\n"
        f"{_HASHTAGS_TT}"
    ).strip()

    # Instagram: full narrative + CTA + hashtags
    instagram = (
        f"{caption_hero}\n\n"
        f"{caption_full}\n\n"
        f"{engagement_hook}\n\n"
        f"{_HASHTAGS_IG}"
    ).strip()

    return {"tiktok": tiktok, "instagram": instagram}


# ── GitHub release upload ──────────────────────────────────────────────────────

def _upload_to_github(
    video_path: Path,
    reel_slug: str,
    dry_run: bool,
    cover_image: Path | None = None,
) -> tuple[str | None, str | None]:
    tag    = f"provenance-{reel_slug}"
    assets = [str(video_path)]
    if cover_image:
        assets.append(str(cover_image))

    if dry_run:
        video_url = f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/reel.mp4"
        image_url = (
            f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/{cover_image.name}"
            if cover_image else None
        )
        print(f"  [dry-run] GitHub release tag: {tag}")
        print(f"  [dry-run] video URL: {video_url}")
        return video_url, image_url

    print(f"  Creating GitHub release '{tag}'...")
    result = subprocess.run(
        [
            "gh", "release", "create", tag,
            *assets,
            "--repo",  GITHUB_REPO,
            "--title", f"Provenance — {reel_slug}",
            "--notes", "Auto-generated by Provenance reel pipeline",
        ],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        if "already exists" in result.stderr:
            print("  Release exists — uploading assets...")
            r2 = subprocess.run(
                ["gh", "release", "upload", tag, *assets,
                 "--repo", GITHUB_REPO, "--clobber"],
                capture_output=True, text=True,
            )
            if r2.returncode != 0:
                print(f"  ✗ Upload failed: {r2.stderr[:200]}")
                return None, None
        else:
            print(f"  ✗ GitHub release failed: {result.stderr[:200]}")
            return None, None

    video_url = f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/reel.mp4"
    image_url = (
        f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/{cover_image.name}"
        if cover_image else None
    )
    print(f"  ✓ {video_url}")
    return video_url, image_url


# ── Buffer GraphQL ─────────────────────────────────────────────────────────────

_CREATE_POST = """
mutation CreatePost($input: CreatePostInput!) {
  createPost(input: $input) {
    ... on PostActionSuccess {
      post { id status dueAt }
    }
    ... on MutationError {
      message
    }
  }
}
"""


def _post_to_buffer(
    client:       httpx.Client,
    channel_id:   str,
    platform:     str,
    text:         str,
    video_url:    str,
    scheduled_at: str | None,
    dry_run:      bool,
) -> bool:
    if dry_run:
        print(f"  [dry-run] {platform}: channel={channel_id}, schedule={scheduled_at or 'queue'}")
        print(f"  Caption ({len(text)} chars): {text[:120]}...")
        return True

    metadata: dict = {}
    if platform == "TikTok":
        metadata["tiktok"] = {"title": text[:150]}
    elif platform == "Instagram":
        metadata["instagram"] = {"type": "reel", "shouldShareToFeed": True}

    variables: dict = {
        "input": {
            "channelId":      channel_id,
            "text":           text,
            "assets":         [{"video": {"url": video_url}}],
            "schedulingType": "automatic",  # default to notification; will override to customScheduled if scheduled_at is provided
            "metadata":       metadata,
        }
    }

    if scheduled_at:
        dt = datetime.fromisoformat(scheduled_at).astimezone(timezone.utc)
        variables["input"]["mode"]  = "customScheduled"
        variables["input"]["dueAt"] = dt.isoformat()
    else:
        variables["input"]["mode"] = "addToQueue"

    r = client.post(BUFFER_GRAPHQL, json={"query": _CREATE_POST, "variables": variables})

    if r.status_code != 200:
        print(f"  ✗ {platform} HTTP {r.status_code}: {r.text[:300]}")
        return False

    data   = r.json()
    errors = data.get("errors")
    if errors:
        print(f"  ✗ {platform} GraphQL error: {errors[0].get('message')}")
        return False

    result = data.get("data", {}).get("createPost", {})
    if "message" in result:
        print(f"  ✗ {platform} Buffer error: {result['message']}")
        print(f"      Full response: {json.dumps(data)[:400]}")
        return False

    post = result.get("post")
    if not post:
        print(f"  ✗ {platform} unexpected response: {json.dumps(data)[:400]}")
        return False

    print(f"  ✓ {platform} queued — id: {post['id']}  status: {post['status']}  due: {post.get('dueAt', 'queue')}")
    return True


# ── Mark posted in hermes.db ───────────────────────────────────────────────────

def _mark_posted(reel_dir: Path, platforms: list[str]) -> None:
    import sqlite3
    db_path = BUSINESS_DIR / "data" / "hermes.db"
    if not db_path.exists():
        return

    config_path = reel_dir / "reel_config.py"
    if not config_path.exists():
        return

    cfg_text  = config_path.read_text()
    id_m      = re.search(r'"lot_id"\s*:\s*"([^"]+)"', cfg_text)
    model_m   = re.search(r'"location_name"\s*:\s*"([^"]+)"', cfg_text)
    if not id_m:
        return

    reel_slug = id_m.group(1)
    model     = model_m.group(1).title() if model_m else reel_slug

    conn = sqlite3.connect(db_path)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS posted_hermes_reels (
            model       TEXT PRIMARY KEY,
            retail_eur  REAL,
            resale_usd  REAL,
            premium_pct REAL,
            reel_slug   TEXT,
            posted_at   TEXT DEFAULT (datetime('now'))
        )
    """)
    # Update platforms field if row already exists; insert otherwise
    existing = conn.execute(
        "SELECT reel_slug FROM posted_hermes_reels WHERE model = ?", (model,)
    ).fetchone()
    if existing:
        conn.execute(
            "UPDATE posted_hermes_reels SET reel_slug = ?, posted_at = datetime('now') WHERE model = ?",
            (reel_slug, model),
        )
    else:
        conn.execute(
            "INSERT OR IGNORE INTO posted_hermes_reels (model, reel_slug) VALUES (?, ?)",
            (model, reel_slug),
        )
    conn.commit()
    conn.close()
    print(f"  ✓ Marked posted in hermes.db (model={model})")


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Post a Provenance Hermès reel to TikTok/Instagram via Buffer."
    )
    parser.add_argument("reel_dir",        help="Reel folder path, e.g. reels/hermes-birkin-30-2026-05-29")
    parser.add_argument("--schedule",      default=None,
                        help="ISO 8601 datetime, e.g. 2026-06-01T19:00:00+07:00")
    parser.add_argument("--no-tiktok",     dest="tiktok",     action="store_false", default=True)
    parser.add_argument("--no-instagram",  dest="instagram",  action="store_false", default=True)
    parser.add_argument("--dry-run",       action="store_true")
    args = parser.parse_args()

    reel_dir      = BUSINESS_DIR / args.reel_dir
    video_path    = reel_dir / "output" / "reel.mp4"
    captions_path = reel_dir / "output" / "captions.md"
    reel_slug     = reel_dir.name

    if not reel_dir.exists():
        print(f"✗ Reel folder not found: {reel_dir}")
        sys.exit(1)
    if not video_path.exists():
        print(f"✗ No reel.mp4 found in {reel_dir / 'output'}")
        sys.exit(1)
    if not args.dry_run and not TOKEN:
        print("✗ PROVENANCE_BUFFER_TOKEN not set in .env")
        sys.exit(1)

    cfg      = _load_config(reel_dir)
    captions = _build_captions(cfg, captions_path)

    model    = cfg.get("location_name", reel_slug)
    retail   = cfg.get("caption_line1", "")
    resale   = cfg.get("caption_line2", "")
    premium  = cfg.get("caption_line3", "")

    print("═" * 62)
    print("  BUFFER POSTER — Provenance")
    print(f"  Reel:    {reel_slug}")
    print(f"  Model:   {model}")
    print(f"  {retail}")
    print(f"  {resale}")
    print(f"  {premium}")
    print(f"  Mode:    {'DRY RUN' if args.dry_run else 'LIVE'}")
    if args.schedule:
        print(f"  Sched:   {args.schedule}")
    else:
        print(f"  Sched:   add to queue")
    print("═" * 62)

    # Step 1 — host video on GitHub
    print("\n▸ Hosting video on GitHub releases...")
    images_dir  = reel_dir / "images"
    cover_image = next(
        (p for p in sorted(images_dir.glob("01_*")) if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}),
        None,
    ) if images_dir.is_dir() else None
    if cover_image:
        print(f"  Cover image: {cover_image.name}")

    video_url, _ = _upload_to_github(video_path, reel_slug, args.dry_run, cover_image)
    if not video_url:
        sys.exit(1)

    # Step 2 — post to Buffer
    print("\n▸ Posting to Buffer...")
    headers = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
    results = []

    with httpx.Client(headers=headers, timeout=30) as client:
        if args.tiktok and (TT_CHANNEL or args.dry_run):
            ok = _post_to_buffer(
                client, TT_CHANNEL or "TT_ID", "TikTok",
                captions["tiktok"], video_url, args.schedule, args.dry_run,
            )
            results.append(("TikTok", ok))
        elif args.tiktok:
            print("  ⚠ PROVENANCE_BUFFER_TIKTOK_ID not set — skipping TikTok")

        if args.instagram and (IG_CHANNEL or args.dry_run):
            ok = _post_to_buffer(
                client, IG_CHANNEL or "IG_ID", "Instagram",
                captions["instagram"], video_url, args.schedule, args.dry_run,
            )
            results.append(("Instagram", ok))
        elif args.instagram and not IG_CHANNEL:
            print("  ⚠ PROVENANCE_BUFFER_INSTAGRAM_ID not set — skipping Instagram")

    # Step 3 — record
    posted_platforms = [p for p, ok in results if ok]
    if posted_platforms and not args.dry_run:
        _mark_posted(reel_dir, posted_platforms)

    print("\n" + "═" * 62)
    for platform, ok in results:
        print(f"  {'✓' if ok else '✗'} {platform}")
    if not results:
        print("  ⚠ No platforms posted — check channel IDs in .env")
    print("═" * 62)


if __name__ == "__main__":
    main()
