#!/usr/bin/env python3
"""
Post a "Beat the Estimate" image card set to Instagram and TikTok via Buffer
GraphQL — a carousel of still images, not a video.

First live run (2026-07-03) surfaced one real Buffer error, now fixed:
Instagram's `type` field only accepts post/story/reel, not "carousel" — a
multi-image carousel is posted as a plain "post" and Buffer infers the
carousel from having multiple image assets. TikTok's metadata shape
(`{"title": ...}`, same as the video poster) has not yet had a live run
confirm or reject it — treat the next live run as that test.

Usage:
    python scripts/post_beat_the_estimate_to_buffer.py output/beat_the_estimate/<date> --dry-run
    python scripts/post_beat_the_estimate_to_buffer.py output/beat_the_estimate/<date>
    python scripts/post_beat_the_estimate_to_buffer.py output/beat_the_estimate/<date> --schedule "2026-07-10T19:00:00+07:00"

Requires in .env (same Buffer app as post_to_buffer.py):
    BUFFER_TOKEN
    BUFFER_INSTAGRAM_ID
    BUFFER_TIKTOK_ID   (optional)
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import httpx
from dotenv import load_dotenv

SCRIPT_DIR   = Path(__file__).resolve().parent
BUSINESS_DIR = SCRIPT_DIR.parent

load_dotenv(BUSINESS_DIR / ".env", override=False)

BUFFER_GRAPHQL = "https://api.buffer.com/graphql"
TOKEN          = os.getenv("BUFFER_TOKEN")
IG_CHANNEL     = os.getenv("BUFFER_INSTAGRAM_ID")
TT_CHANNEL     = os.getenv("BUFFER_TIKTOK_ID")

GITHUB_REPO = "alexsnowschool-business/alexsnowschool-business.github.io"


def _upload_images_to_github(image_paths: list[Path], slug: str, dry_run: bool) -> list[str] | None:
    tag = f"beat-the-estimate-{slug}"

    if dry_run:
        urls = [f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/{p.name}" for p in image_paths]
        print(f"  [dry-run] would upload {len(image_paths)} images to GitHub release: {tag}")
        return urls

    print(f"  Creating GitHub release '{tag}'...")
    result = subprocess.run(
        [
            "gh", "release", "create", tag,
            *[str(p) for p in image_paths],
            "--repo",  GITHUB_REPO,
            "--title", f"Beat the Estimate — {slug}",
            "--notes", "Auto-generated by beat_the_estimate.py",
        ],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        if "already exists" in result.stderr:
            print("  Release exists — uploading assets...")
            r2 = subprocess.run(
                ["gh", "release", "upload", tag, *[str(p) for p in image_paths],
                 "--repo", GITHUB_REPO, "--clobber"],
                capture_output=True, text=True,
            )
            if r2.returncode != 0:
                print(f"  ✗ Upload failed: {r2.stderr[:200]}")
                return None
        else:
            print(f"  ✗ GitHub release failed: {result.stderr[:200]}")
            return None

    urls = [f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/{p.name}" for p in image_paths]
    print(f"  ✓ Uploaded {len(urls)} images")
    return urls


_CREATE_POST = """
mutation CreatePost($input: CreatePostInput!) {
  createPost(input: $input) {
    ... on PostActionSuccess {
      post { id status dueAt }
    }
    ... on MutationError {
      message
    }
  }
}
"""


def _post_to_buffer(
    client: httpx.Client,
    channel_id: str,
    platform: str,
    text: str,
    image_urls: list[str],
    scheduled_at: str | None,
    dry_run: bool,
) -> bool:
    if dry_run:
        print(f"  [dry-run] {platform}: channel={channel_id}, images={len(image_urls)}, schedule={scheduled_at or 'queue'}")
        print(f"  Caption: {text[:120]}...")
        return True

    # Confirmed against a live Buffer error response: Instagram's `type` only
    # accepts post/story/reel — a multi-image carousel is just a "post" with
    # multiple image assets, Buffer infers the carousel from the asset count.
    metadata: dict = {}
    if platform == "Instagram":
        metadata["instagram"] = {"type": "post", "shouldShareToFeed": True}
    elif platform == "TikTok":
        metadata["tiktok"] = {"title": text[:150]}

    variables: dict = {
        "input": {
            "channelId":      channel_id,
            "text":           text,
            "assets":         [{"image": {"url": url}} for url in image_urls],
            "schedulingType": "automatic",
            "metadata":       metadata,
        }
    }

    if scheduled_at:
        dt = datetime.fromisoformat(scheduled_at).astimezone(timezone.utc)
        variables["input"]["mode"]  = "customScheduled"
        variables["input"]["dueAt"] = dt.isoformat()
    else:
        variables["input"]["mode"] = "addToQueue"

    r = client.post(BUFFER_GRAPHQL, json={"query": _CREATE_POST, "variables": variables})

    if r.status_code != 200:
        print(f"  ✗ {platform} HTTP {r.status_code}: {r.text[:300]}")
        return False

    data = r.json()
    if data.get("errors"):
        print(f"  ✗ {platform} GraphQL error: {data['errors'][0].get('message')}")
        return False

    result = data.get("data", {}).get("createPost", {})
    if "message" in result:
        print(f"  ✗ {platform} Buffer error: {result['message']}")
        print(f"      Full response: {json.dumps(data)[:400]}")
        return False

    post = result.get("post")
    if not post:
        print(f"  ✗ {platform} unexpected response: {json.dumps(data)[:400]}")
        return False

    print(f"  ✓ {platform} queued — id: {post['id']}  status: {post['status']}  due: {post.get('dueAt', 'queue')}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Post Beat the Estimate cards to Buffer as an image carousel.")
    parser.add_argument("cards_dir", help="Folder from beat_the_estimate.py, e.g. output/beat_the_estimate/2026-07-10")
    parser.add_argument("--schedule", default=None, help="ISO 8601 datetime, e.g. 2026-07-10T19:00:00+07:00")
    parser.add_argument("--no-instagram", dest="instagram", action="store_false", default=True)
    parser.add_argument("--no-tiktok",    dest="tiktok",    action="store_false", default=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    cards_dir = BUSINESS_DIR / args.cards_dir
    meta_path = cards_dir / "meta.json"

    if not cards_dir.is_dir():
        print(f"✗ Folder not found: {cards_dir}")
        sys.exit(1)
    if not meta_path.exists():
        print(f"✗ No meta.json in {cards_dir} — did beat_the_estimate.py generate this folder?")
        sys.exit(1)
    if not args.dry_run and not TOKEN:
        print("✗ BUFFER_TOKEN not set in .env")
        sys.exit(1)

    meta   = json.loads(meta_path.read_text())
    images = sorted(cards_dir.glob("*.png"))
    if not images:
        print(f"✗ No PNG cards found in {cards_dir}")
        sys.exit(1)

    print("═" * 60)
    print("  BUFFER POSTER — Beat the Estimate (images)")
    print(f"  Folder: {cards_dir.name}")
    print(f"  Title:  {meta.get('title')}")
    print(f"  Cards:  {len(images)}")
    print(f"  Mode:   {'DRY RUN' if args.dry_run else 'LIVE'}")
    print("═" * 60)

    try:
        from ai_content import generate_beat_the_estimate_social_caption
    except ImportError:
        print("✗ Could not import ai_content — run from the project root.")
        sys.exit(1)

    print("\n▸ Generating social captions...")
    captions = generate_beat_the_estimate_social_caption(meta["lots"], meta.get("title", ""))
    if not captions:
        print("✗ Caption generation failed — check OPENROUTER_API_KEY in .env.")
        sys.exit(1)

    print("\n▸ Hosting images on GitHub releases...")
    image_urls = _upload_images_to_github(images, cards_dir.name, args.dry_run)
    if not image_urls:
        sys.exit(1)

    print("\n▸ Posting to Buffer...")
    headers = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
    results = []

    with httpx.Client(headers=headers, timeout=30) as client:
        if args.instagram and (IG_CHANNEL or args.dry_run):
            ok = _post_to_buffer(client, IG_CHANNEL or "IG_ID", "Instagram",
                                 captions["instagram"], image_urls, args.schedule, args.dry_run)
            results.append(("Instagram", ok))
        elif args.instagram:
            print("  ⚠ BUFFER_INSTAGRAM_ID not set — skipping")

        if args.tiktok and (TT_CHANNEL or args.dry_run):
            ok = _post_to_buffer(client, TT_CHANNEL or "TT_ID", "TikTok",
                                 captions["tiktok"], image_urls, args.schedule, args.dry_run)
            results.append(("TikTok", ok))
        elif args.tiktok:
            print("  ⚠ BUFFER_TIKTOK_ID not set — skipping")

    print("\n" + "═" * 60)
    for platform, ok in results:
        print(f"  {'✓' if ok else '✗'} {platform}")
    print("═" * 60)


if __name__ == "__main__":
    main()
