// data.js — Who Owns What
// AUTO-GENERATED by export_data_js.py — 2026-08-19 14:04 UTC
// Source of truth: data/whoownswhat.db
// DO NOT EDIT MANUALLY — run export_data_js.py after any DB change.

const WOW_DATA = {
    "meta": {
        "countries": {
            "germany": {
                "label": "Germany",
                "flag": "DE",
                "currency": "EUR",
                "active": true
            },
            "us": {
                "label": "United States",
                "flag": "US",
                "currency": "USD",
                "active": false
            },
            "uk": {
                "label": "United Kingdom",
                "flag": "GB",
                "currency": "GBP",
                "active": false
            },
            "france": {
                "label": "France",
                "flag": "FR",
                "currency": "EUR",
                "active": false
            }
        }
    },
    "entities": {
        "adidas": {
            "type": "company",
            "country": "germany",
            "name": "Adidas AG",
            "summary": "Adidas AG is a German multinational athletic apparel and footwear corporation headquartered in Herzogenaurach, Germany. It is the largest sportswear manufacturer in Europe, and the second largest in the world, after Nike. It is the holding company for the Adidas Group, which also owns an 8.33% stake in the football club Bayern Munich, and Runtastictrian fitness technology company. Adidas's revenue for 2024 was listed at €23 billion. Adidas is known for its brand image, extensive long origin history for participating in sponsoring athletes, and gear in the FIFA World Cup series. The brand is al",
            "ticker": "ADS",
            "exchange": "",
            "sector": "textile industry",
            "headquarters": "Herzogenaurach",
            "founded": "1924",
            "employees": "60,617",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "compensation": {
                "ceeName": "Bjørn Gulden",
                "ceoTitle": null,
                "ceoTotal": null,
                "ceoSalary": null,
                "ceoEquity": null,
                "medianWorker": null,
                "ceoWorkerRatio": null,
                "source": "Wikipedia / Wikidata",
                "url": "https://en.wikipedia.org/wiki/Adidas"
            },
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Adidas AG",
                    "url": "https://en.wikipedia.org/wiki/Adidas"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Adidas AG — official website",
                    "url": "https://www.adidas.com/"
                }
            ]
        },
        "airbus": {
            "type": "company",
            "country": "germany",
            "name": "Airbus SE",
            "summary": "Airbus SE is a European aerospace corporation. While the company's primary business is the design and manufacture of commercial aircraft, it also operates separate divisions for Defence and Space and Helicopters. Airbus has long been the world's leading helicopter manufacturer and, in 2019, emerged as the world's largest manufacturer of airliners.",
            "ticker": "AIR",
            "exchange": "",
            "sector": "aircraft and space construction",
            "headquarters": "Blagnac",
            "founded": "1969",
            "employees": "80,895",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "compensation": {
                "ceeName": "Tom Enders",
                "ceoTitle": null,
                "ceoTotal": null,
                "ceoSalary": null,
                "ceoEquity": null,
                "medianWorker": null,
                "ceoWorkerRatio": null,
                "source": "Wikipedia / Wikidata",
                "url": "https://en.wikipedia.org/wiki/Airbus"
            },
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Airbus SE",
                    "url": "https://en.wikipedia.org/wiki/Airbus"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Airbus SE — official website",
                    "url": "https://www.airbus.com/"
                }
            ]
        },
        "allianz": {
            "type": "company",
            "country": "germany",
            "name": "Allianz SE",
            "summary": "Allianz SE is a German multinational financial services company headquartered in Munich, Germany. Its core businesses are insurance and asset management.",
            "ticker": "ALV",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Allianz SE",
                    "url": "https://en.wikipedia.org/wiki/Allianz"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "sap": {
            "type": "company",
            "country": "germany",
            "name": "SAP SE",
            "summary": "SAP SE is the world's leading enterprise application software company, with customers in over 180 countries. Co-founded in 1972 by Hasso Plattner and colleagues as a spin-off from IBM Germany.",
            "ticker": "SAP",
            "exchange": "XETRA / NYSE (ADR)",
            "sector": "Enterprise Software / Technology",
            "headquarters": "Walldorf, Baden-Württemberg, Germany",
            "founded": "1972",
            "employees": "107,000",
            "revenue": "€31.2 billion (2023)",
            "marketCap": "~€230 billion",
            "shareholders": [
                {
                    "name": "Hasso Plattner (+ HHP Research Foundation)",
                    "stake": "~9.5%",
                    "type": "Co-Founder",
                    "source": "SAP SE Annual Report 2023 / Bundesanzeiger",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "name": "Vanguard Group",
                    "stake": "~4.8%",
                    "type": "Institutional",
                    "source": "BaFin voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "BlackRock Inc.",
                    "stake": "~4.0%",
                    "type": "Institutional",
                    "source": "BaFin voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "Free float",
                    "stake": "~78%",
                    "type": "Public",
                    "source": "SAP SE Investor Relations",
                    "url": "https://www.sap.com/investors.html"
                }
            ],
            "compensation": {
                "ceeName": "Christian Klein",
                "ceoTitle": "Chief Executive Officer (Vorstandsvorsitzender)",
                "ceoTotal": "€12.8M",
                "ceoSalary": "€900K",
                "ceoEquity": "€10.2M (performance shares + RSUs)",
                "medianWorker": "~€95,000",
                "ceoWorkerRatio": "~135:1",
                "source": "SAP SE Annual Report 2023 (Remuneration Report)",
                "url": "https://www.sap.com/investors/en/reports.html"
            },
            "lobbying": [
                {
                    "year": "2024",
                    "amount": "€3.3M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "year": "2023",
                    "amount": "€2.9M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "year": "2022",
                    "amount": "€2.4M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                }
            ],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "SAP lobbies through BITKOM and DIGITALEUROPE. Key topics: AI Act, data regulation.",
                "source": "Parteiengesetz §25 / BITKOM / Bundestag Lobbyregister",
                "url": "https://lobbyregister.bundestag.de"
            },
            "fines": [
                {
                    "year": "2024",
                    "description": "SAP agreed to pay ~$222M to resolve U.S. DOJ FCPA investigation: bribery of government officials in South Africa, Malawi, Tanzania, Ghana, Indonesia, and Panama.",
                    "source": "U.S. DOJ / SEC (January 2024)",
                    "url": "https://www.justice.gov/opa/pr/sap-agrees-pay-over-220-million-resolve-foreign-corrupt-practices-act-charges"
                }
            ],
            "labor": [
                {
                    "description": "SAP announced global restructuring affecting ~8,000 employees (7.5% of workforce) in January 2024, shifting resources toward AI.",
                    "source": "SAP press release / Handelsblatt (2024)",
                    "url": "https://news.sap.com"
                }
            ],
            "competitors": [
                "Oracle Corp. (ORCL, NYSE)",
                "Microsoft Dynamics",
                "Salesforce (CRM)",
                "Workday (WDAY)"
            ],
            "sources": [
                {
                    "title": "SAP SE Annual Report 2023",
                    "url": "https://www.sap.com/investors/en/reports.html"
                },
                {
                    "title": "Bundestag Lobbyregister — SAP SE",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "title": "U.S. DOJ — SAP FCPA settlement (2024)",
                    "url": "https://www.justice.gov/opa/pr/sap-agrees-pay-over-220-million-resolve-foreign-corrupt-practices-act-charges"
                }
            ]
        },
        "volkswagen": {
            "type": "company",
            "country": "germany",
            "name": "Volkswagen AG",
            "summary": "Volkswagen AG is Europe's largest automaker and one of the world's largest by vehicle sales. Its brands include VW, Audi, Porsche, SEAT, Skoda, Lamborghini, Bentley, and MAN. The German state of Lower Saxony holds a blocking minority stake under the VW Law (Volkswagen-Gesetz).",
            "ticker": "VOW3",
            "exchange": "XETRA / Frankfurt Stock Exchange",
            "sector": "Automotive",
            "headquarters": "Wolfsburg, Lower Saxony, Germany",
            "founded": "1937",
            "employees": "684,000",
            "revenue": "€293 billion (2023)",
            "marketCap": "~€55 billion",
            "shareholders": [
                {
                    "name": "Porsche Automobil Holding SE",
                    "stake": "53.3% (voting)",
                    "type": "Family / Strategic (Piech & Porsche families)",
                    "source": "Volkswagen AG Annual Report 2023 / Bundesanzeiger",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "name": "State of Lower Saxony (Niedersachsen)",
                    "stake": "11.8% (blocking minority)",
                    "type": "Government / Public Entity",
                    "source": "Volkswagen AG Annual Report 2023",
                    "url": "https://annualreport2023.volkswagen-group.com"
                },
                {
                    "name": "Qatar Investment Authority",
                    "stake": "14.6%",
                    "type": "Sovereign Wealth Fund",
                    "source": "VW Annual Report 2023 / BaFin",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "Vanguard Group",
                    "stake": "~1.5% (ordinary shares)",
                    "type": "Institutional",
                    "source": "BaFin voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "Free float",
                    "stake": "~18.8%",
                    "type": "Public",
                    "source": "Volkswagen AG Investor Relations",
                    "url": "https://www.volkswagenag.com/en/InvestorRelations.html"
                }
            ],
            "compensation": {
                "ceeName": "Oliver Blume",
                "ceoTitle": "Chairman of the Board of Management",
                "ceoTotal": "€10.3M",
                "ceoSalary": "€1.3M",
                "ceoEquity": "€6.2M (long-term incentive)",
                "medianWorker": "~€62,000",
                "ceoWorkerRatio": "~166:1",
                "source": "Volkswagen AG Geschäftsbericht 2023 (Vergütungsbericht)",
                "url": "https://annualreport2023.volkswagen-group.com"
            },
            "lobbying": [
                {
                    "year": "2024",
                    "amount": "€6.2M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "year": "2023",
                    "amount": "€5.8M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "year": "2022",
                    "amount": "€4.9M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                }
            ],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations. VW engages through VDA (Verband der Automobilindustrie).",
                "source": "Parteiengesetz §25 / Bundestag Lobbyregister",
                "url": "https://lobbyregister.bundestag.de"
            },
            "fines": [
                {
                    "year": "2015–2021",
                    "description": "Dieselgate: VW admitted to defeat devices in ~11M diesel vehicles. Total costs >€30 billion globally.",
                    "source": "U.S. DOJ / Staatsanwaltschaft Braunschweig",
                    "url": "https://www.justice.gov/opa/pr/volkswagen-ag-agrees-plead-guilty-and-pay-43-billion-connection-allegations-conspiracy-and"
                }
            ],
            "labor": [
                {
                    "description": "VW has full co-determination (Mitbestimmung): Supervisory Board is 50% employee representatives. IG Metall holds several seats.",
                    "source": "VW Corporate Governance / IG Metall",
                    "url": "https://www.igmetall.de"
                },
                {
                    "description": "In 2024, VW announced closure of at least three German plants and 35,000+ job cuts. IG Metall launched strikes.",
                    "source": "Handelsblatt / Reuters (2024)",
                    "url": "https://www.handelsblatt.com"
                }
            ],
            "competitors": [
                "BMW AG (BMW, XETRA)",
                "Mercedes-Benz Group AG (MBG, XETRA)",
                "Stellantis N.V. (STLA)",
                "Toyota Motor Corp.",
                "Renault Group"
            ],
            "sources": [
                {
                    "title": "Volkswagen AG Annual Report 2023",
                    "url": "https://annualreport2023.volkswagen-group.com"
                },
                {
                    "title": "Bundestag Lobbyregister — Volkswagen AG",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "title": "BaFin — VW voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "U.S. DOJ — Volkswagen Dieselgate plea",
                    "url": "https://www.justice.gov/opa/pr/volkswagen-ag-agrees-plead-guilty-and-pay-43-billion-connection-allegations-conspiracy-and"
                }
            ]
        },
        "dieter-schwarz": {
            "type": "person",
            "country": "germany",
            "name": "Dieter Schwarz",
            "summary": "Dieter Schwarz owns 100% of the Schwarz Group — parent of Lidl (~12,000 stores, 31 countries) and Kaufland. Neither company is publicly listed. Schwarz has never given a public interview.",
            "title": "Owner, Schwarz Group (Lidl & Kaufland)",
            "nationality": "German",
            "born": "1939",
            "netWorth": "€47 billion (~$51B)",
            "netWorthRank": "#1 wealthiest in Germany",
            "netWorthSource": "Manager Magazin Reichenliste 2024",
            "netWorthUrl": "https://www.manager-magazin.de/finanzen/reichenliste/",
            "assets": [
                {
                    "name": "Schwarz Group (Lidl + Kaufland)",
                    "description": "100% private. Combined revenue: ~€150 billion (2023). Europe's largest retailer by revenue.",
                    "source": "Bundesanzeiger / Manager Magazin estimates",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "name": "Dieter Schwarz Stiftung",
                    "description": "Foundation funding Technische Hochschule Heilbronn and regional education projects. Assets: ~€5B+.",
                    "source": "Dieter Schwarz Stiftung",
                    "url": "https://www.dieter-schwarz-stiftung.de"
                }
            ],
            "boardMemberships": [
                {
                    "org": "Schwarz Group",
                    "role": "Sole owner (no public board)",
                    "source": "Schwarz Gruppe / Bundesanzeiger"
                }
            ],
            "foundations": [
                {
                    "name": "Dieter Schwarz Stiftung",
                    "description": "Funds Technische Hochschule Heilbronn, Bildungscampus Heilbronn (€600M+ campus), and social welfare.",
                    "source": "Dieter Schwarz Stiftung",
                    "url": "https://www.dieter-schwarz-stiftung.de"
                }
            ],
            "politicalSpending": {
                "pac": "None",
                "summary": "No documented political donations. German law prohibits corporate party donations. Schwarz is intensely private.",
                "total2024": null,
                "source": "Parteiengesetz §25 / no public records",
                "url": "https://lobbyregister.bundestag.de"
            },
            "timeline": [
                {
                    "year": "1963",
                    "event": "Joins father Josef Schwarz's wholesale food company in Heilbronn."
                },
                {
                    "year": "1973",
                    "event": "Opens first Lidl store in Ludwigshafen, modelled on Aldi's discount concept."
                },
                {
                    "year": "1988",
                    "event": "Lidl expands into France — beginning European rollout."
                },
                {
                    "year": "2000",
                    "event": "Schwarz Group becomes Germany's largest food retailer."
                },
                {
                    "year": "2015",
                    "event": "Lidl enters the U.S. market."
                },
                {
                    "year": "2024",
                    "event": "Schwarz Group revenue surpasses €150B — Europe's largest retailer."
                }
            ],
            "sources": [
                {
                    "title": "Manager Magazin Reichenliste 2024",
                    "url": "https://www.manager-magazin.de/finanzen/reichenliste/"
                },
                {
                    "title": "Bundesanzeiger — Schwarz Gruppe filings (limited)",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "Dieter Schwarz Stiftung",
                    "url": "https://www.dieter-schwarz-stiftung.de"
                }
            ]
        },
        "hasso-plattner": {
            "type": "person",
            "country": "germany",
            "name": "Hasso Plattner",
            "summary": "Hasso Plattner co-founded SAP SE in 1972 with four IBM Germany colleagues. He chairs the Supervisory Board and holds ~9.5% of SAP shares (via personal holdings and HHP Research Foundation). He founded and endowed the Hasso Plattner Institute (HPI) at the University of Potsdam.",
            "title": "Co-founder & Supervisory Board Chairman, SAP SE",
            "nationality": "German",
            "born": "1944",
            "netWorth": "€14 billion (~$15B)",
            "netWorthRank": "Top 10 wealthiest in Germany",
            "netWorthSource": "Manager Magazin Reichenliste 2024",
            "netWorthUrl": "https://www.manager-magazin.de/finanzen/reichenliste/",
            "assets": [
                {
                    "name": "SAP SE (~9.5% stake)",
                    "description": "Worth ~€22B at peak SAP market cap (~€230B, 2024).",
                    "source": "SAP SE Annual Report 2023 / BaFin",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "Hasso Plattner Institute (HPI), Potsdam",
                    "description": "Germany's leading IT institute, co-located with University of Potsdam. Plattner donated €100M+ in initial endowment.",
                    "source": "HPI official website",
                    "url": "https://hpi.de"
                }
            ],
            "boardMemberships": [
                {
                    "org": "SAP SE",
                    "role": "Chairman of the Supervisory Board",
                    "source": "SAP SE Annual Report 2023"
                }
            ],
            "foundations": [
                {
                    "name": "Hasso Plattner Foundation",
                    "description": "Funds HPI Potsdam and HPI School of Design Thinking. Total donations exceed €700M.",
                    "source": "HPI / Hasso Plattner Foundation",
                    "url": "https://hpi.de/en/about-hpi/hasso-plattner.html"
                }
            ],
            "politicalSpending": {
                "pac": "None",
                "summary": "No documented political donations. Influence operates through SAP, HPI, and BITKOM.",
                "total2024": null,
                "source": "No public records",
                "url": "https://lobbyregister.bundestag.de"
            },
            "timeline": [
                {
                    "year": "1968",
                    "event": "Joins IBM Germany in Mannheim."
                },
                {
                    "year": "1972",
                    "event": "Co-founds SAP with four IBM colleagues in Weinheim."
                },
                {
                    "year": "1998",
                    "event": "Founds and endows the Hasso Plattner Institute at University of Potsdam."
                },
                {
                    "year": "2003",
                    "event": "Steps down as SAP co-CEO; becomes Supervisory Board Chairman."
                },
                {
                    "year": "2010",
                    "event": "SAP launches HANA (in-memory database) — Plattner's core architectural concept."
                },
                {
                    "year": "2023",
                    "event": "SAP market cap surpasses €200B — Europe's most valuable software company."
                }
            ],
            "sources": [
                {
                    "title": "Manager Magazin Reichenliste 2024",
                    "url": "https://www.manager-magazin.de/finanzen/reichenliste/"
                },
                {
                    "title": "SAP SE Annual Report 2023",
                    "url": "https://www.sap.com/investors/en/reports.html"
                },
                {
                    "title": "Hasso Plattner Institute — About",
                    "url": "https://hpi.de/en/about-hpi/hasso-plattner.html"
                }
            ]
        },
        "susanne-klatten": {
            "type": "person",
            "country": "germany",
            "name": "Susanne Klatten",
            "summary": "Susanne Klatten is the daughter of Herbert Quandt, who rescued BMW from bankruptcy in 1959. Together with her brother Stefan Quandt, she controls ~45% of BMW AG. She also holds a majority stake in specialty chemicals company Altana AG.",
            "title": "Billionaire investor; 19.2% stake in BMW AG; majority owner of Altana AG",
            "nationality": "German",
            "born": "1962",
            "netWorth": "€27 billion (~$29B)",
            "netWorthRank": "#2 wealthiest woman in Germany",
            "netWorthSource": "Manager Magazin Reichenliste 2024",
            "netWorthUrl": "https://www.manager-magazin.de/finanzen/reichenliste/",
            "assets": [
                {
                    "name": "BMW AG (BMW, XETRA)",
                    "description": "19.2% stake — ~€12B at 2024 market prices.",
                    "source": "BMW AG Annual Report 2023 / BaFin",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "Altana AG (majority stake via SKion GmbH)",
                    "description": "Leading specialty chemicals company. EBITDA ~€600M. Privately held.",
                    "source": "Bundesanzeiger / Altana AG",
                    "url": "https://www.altana.de"
                },
                {
                    "name": "SKion GmbH",
                    "description": "Personal holding company for all industrial and financial investments.",
                    "source": "Bundesanzeiger",
                    "url": "https://www.bundesanzeiger.de"
                }
            ],
            "boardMemberships": [
                {
                    "org": "BMW AG",
                    "role": "Member of the Supervisory Board (shareholder side)",
                    "source": "BMW AG Annual Report 2023"
                },
                {
                    "org": "Altana AG",
                    "role": "Majority owner and Supervisory Board member",
                    "source": "Altana AG"
                }
            ],
            "foundations": [
                {
                    "name": "Philanthropic activity via SKion GmbH (informal)",
                    "description": "Donates to medical research (bone marrow, cancer) and arts organisations. No major named foundation.",
                    "source": "Manager Magazin",
                    "url": "https://www.manager-magazin.de"
                }
            ],
            "politicalSpending": {
                "pac": "None",
                "summary": "No documented political donations. German law prohibits corporate party donations.",
                "total2024": null,
                "source": "Parteiengesetz §25 / no public records",
                "url": "https://lobbyregister.bundestag.de"
            },
            "timeline": [
                {
                    "year": "1962",
                    "event": "Born in Munich to Herbert and Johanna Quandt."
                },
                {
                    "year": "1982",
                    "event": "Studies business under a pseudonym to avoid media attention."
                },
                {
                    "year": "1997",
                    "event": "Joins the BMW Supervisory Board."
                },
                {
                    "year": "2003",
                    "event": "Takes majority control of Altana AG."
                },
                {
                    "year": "2008",
                    "event": "Subject of blackmail by fraudster Helg Sgarbi; resulting criminal conviction."
                },
                {
                    "year": "2016",
                    "event": "Named Germany's wealthiest woman by Manager Magazin."
                },
                {
                    "year": "2023",
                    "event": "BMW Group reports record profits; BMW stake exceeds €11B."
                }
            ],
            "sources": [
                {
                    "title": "Manager Magazin Reichenliste 2024",
                    "url": "https://www.manager-magazin.de/finanzen/reichenliste/"
                },
                {
                    "title": "BMW AG Annual Report 2023",
                    "url": "https://www.bmwgroup.com/en/investor-relations/financial-reports.html"
                },
                {
                    "title": "BaFin — BMW voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Forbes — Susanne Klatten",
                    "url": "https://www.forbes.com/profile/susanne-klatten/"
                }
            ]
        }
    },
    "factCards": [
        {
            "category": "CEO Pay · Germany",
            "headline": "The average DAX 40 CEO earns approximately 50× the median German worker's wage.",
            "detail": "Average total compensation for a DAX 40 CEO was €7.8M in 2022, vs. a median German worker wage of ~€40,500. Germany's ratio is lower than the U.S. S&P 500 average (272×) due to co-determination laws and collective bargaining.",
            "source": "DSW / Handelsblatt CEO pay study 2023 / Statista",
            "url": "https://www.statista.com/statistics/462682/germany-average-wages/"
        },
        {
            "category": "Lobbying · Germany",
            "headline": "Germany's mandatory Bundestag Lobby Register launched in 2022. Over 6,000 organisations are registered.",
            "detail": "The Lobbyregistergesetz (mandatory lobbying registration law) came into force in January 2022. Organisations must disclose lobbying budget, number of lobbyists, and covered issues. BDI and VDA are among the largest registered spenders.",
            "source": "Bundestag Lobbyregister / Lobbycontrol e.V.",
            "url": "https://lobbyregister.bundestag.de"
        },
        {
            "category": "Corporate Ownership · Germany",
            "headline": "German law prohibits corporations from donating directly to political parties.",
            "detail": "Parteiengesetz §25 prohibits donations from public companies, state-adjacent entities, and organisations significantly publicly funded. Individual donations over €10,000 must be published; over €50,000 must be published immediately.",
            "source": "Parteiengesetz §25 / Bundeszentrale für politische Bildung",
            "url": "https://www.gesetze-im-internet.de/partg/__25.html"
        },
        {
            "category": "Quandt Family · BMW",
            "headline": "The Quandt siblings control 45% of BMW AG — worth over €27 billion combined.",
            "detail": "Stefan Quandt (25.8%) and Susanne Klatten (19.2%) control a blocking minority in BMW AG. Their father Herbert Quandt rescued BMW from bankruptcy in 1959 by acquiring his majority stake.",
            "source": "BMW AG Annual Report 2023 / Manager Magazin",
            "url": "https://www.bmwgroup.com/en/investor-relations/financial-reports.html"
        },
        {
            "category": "Dieselgate · Volkswagen",
            "headline": "VW's emissions scandal cost over €30 billion in fines, settlements, and remediation.",
            "detail": "In 2015, Volkswagen admitted to defeat devices in ~11M diesel vehicles. Total cost >€30B globally: $2.8B U.S. criminal fine, $1.5B civil settlement, €1B German fine.",
            "source": "U.S. DOJ / Staatsanwaltschaft Braunschweig / Reuters",
            "url": "https://www.justice.gov/opa/pr/volkswagen-ag-agrees-plead-guilty-and-pay-43-billion-connection-allegations-conspiracy-and"
        },
        {
            "category": "State Ownership · Germany",
            "headline": "The German Federal Government owns approximately 27.8% of Deutsche Telekom.",
            "detail": "Deutsche Telekom was privatised from Deutsche Bundespost in 1995, but the Federal Government retained its stake via KfW Bankengruppe. Germany also holds direct or indirect majority stakes in Deutsche Post, Deutsche Bahn, and partial stakes in Lufthansa.",
            "source": "Beteiligungsbericht des Bundes / Bundesministerium der Finanzen",
            "url": "https://www.bundesregierung.de"
        }
    ]
};
