// data.js — Who Owns What
// AUTO-GENERATED by export_data_js.py — 2026-08-22 06:28 UTC
// Source of truth: data/whoownswhat.db
// DO NOT EDIT MANUALLY — run export_data_js.py after any DB change.

const WOW_DATA = {
    "meta": {
        "countries": {
            "germany": {
                "label": "Germany",
                "flag": "DE",
                "currency": "EUR",
                "active": true
            },
            "us": {
                "label": "United States",
                "flag": "US",
                "currency": "USD",
                "active": false
            },
            "uk": {
                "label": "United Kingdom",
                "flag": "GB",
                "currency": "GBP",
                "active": false
            },
            "france": {
                "label": "France",
                "flag": "FR",
                "currency": "EUR",
                "active": false
            }
        }
    },
    "entities": {
        "adidas": {
            "type": "company",
            "country": "germany",
            "name": "Adidas AG",
            "summary": "Adidas AG is a German multinational athletic apparel and footwear corporation headquartered in Herzogenaurach, Germany. It is the largest sportswear manufacturer in Europe, and the second largest in the world, after Nike. It is the holding company for the Adidas Group, which also owns an 8.33% stake in the football club Bayern Munich, and Runtastictrian fitness technology company. Adidas's revenue for 2024 was listed at €23 billion. Adidas is known for its brand image, extensive long origin history for participating in sponsoring athletes, and gear in the FIFA World Cup series. The brand is al",
            "ticker": "ADS",
            "exchange": "",
            "sector": "textile industry",
            "headquarters": "Herzogenaurach",
            "founded": "1924",
            "employees": "60,617",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "compensation": {
                "ceeName": "Bjørn Gulden",
                "ceoTitle": null,
                "ceoTotal": null,
                "ceoSalary": null,
                "ceoEquity": null,
                "medianWorker": null,
                "ceoWorkerRatio": null,
                "source": "Wikipedia / Wikidata",
                "url": "https://en.wikipedia.org/wiki/Adidas"
            },
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Adidas AG",
                    "url": "https://en.wikipedia.org/wiki/Adidas"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Adidas AG — official website",
                    "url": "https://www.adidas.com/"
                }
            ]
        },
        "airbus": {
            "type": "company",
            "country": "germany",
            "name": "Airbus SE",
            "summary": "Airbus SE is a European aerospace corporation. While the company's primary business is the design and manufacture of commercial aircraft, it also operates separate divisions for Defence and Space and Helicopters. Airbus has long been the world's leading helicopter manufacturer and, in 2019, emerged as the world's largest manufacturer of airliners.",
            "ticker": "AIR",
            "exchange": "",
            "sector": "aircraft and space construction",
            "headquarters": "Blagnac",
            "founded": "1969",
            "employees": "80,895",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "compensation": {
                "ceeName": "Tom Enders",
                "ceoTitle": null,
                "ceoTotal": null,
                "ceoSalary": null,
                "ceoEquity": null,
                "medianWorker": null,
                "ceoWorkerRatio": null,
                "source": "Wikipedia / Wikidata",
                "url": "https://en.wikipedia.org/wiki/Airbus"
            },
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Airbus SE",
                    "url": "https://en.wikipedia.org/wiki/Airbus"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Airbus SE — official website",
                    "url": "https://www.airbus.com/"
                }
            ]
        },
        "allianz": {
            "type": "company",
            "country": "germany",
            "name": "Allianz SE",
            "summary": "Allianz SE is a German multinational financial services company headquartered in Munich, Germany. Its core businesses are insurance and asset management.",
            "ticker": "ALV",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Allianz SE",
                    "url": "https://en.wikipedia.org/wiki/Allianz"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "basf": {
            "type": "company",
            "country": "germany",
            "name": "BASF SE",
            "summary": "BASF SE, an initialism of its original name Badische Anilin- & Soda-Fabrik, is a German multinational company and the largest chemical producer in the world. Its headquarters is located in Ludwigshafen, Germany.",
            "ticker": "BAS",
            "exchange": "",
            "sector": "chemical industry",
            "headquarters": "Ludwigshafen",
            "founded": "1865",
            "employees": "115,490",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "compensation": {
                "ceeName": "Martin Brudermüller",
                "ceoTitle": null,
                "ceoTotal": null,
                "ceoSalary": null,
                "ceoEquity": null,
                "medianWorker": null,
                "ceoWorkerRatio": null,
                "source": "Wikipedia / Wikidata",
                "url": "https://en.wikipedia.org/wiki/BASF"
            },
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — BASF SE",
                    "url": "https://en.wikipedia.org/wiki/BASF"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "BASF SE — official website",
                    "url": "https://www.basf.com"
                }
            ]
        },
        "bmw": {
            "type": "company",
            "country": "germany",
            "name": "BMW AG",
            "summary": "Bayerische Motoren Werke AG, trading as BMW Group, is a German multinational conglomerate manufacturer of luxury vehicles and motorcycles headquartered in Munich, Germany. The moniker \"BMW \" first came into use when the German firm Rapp Motorenwerke changed its name to Bayerische Motoren Werke GmbH in 1917. Thereafter, in 1922, the name and assets of BMW GmbH were transferred to the aircraft manufacturer Bayerische Flugzeugwerke AG, thereby giving rise to the company known today as BMW AG.",
            "ticker": "BMW",
            "exchange": "",
            "sector": "automotive industry",
            "headquarters": "Munich",
            "founded": "1916",
            "employees": "118,909",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "compensation": {
                "ceeName": "Oliver Zipse",
                "ceoTitle": null,
                "ceoTotal": null,
                "ceoSalary": null,
                "ceoEquity": null,
                "medianWorker": null,
                "ceoWorkerRatio": null,
                "source": "Wikipedia / Wikidata",
                "url": "https://en.wikipedia.org/wiki/BMW"
            },
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — BMW AG",
                    "url": "https://en.wikipedia.org/wiki/BMW"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "BMW AG — official website",
                    "url": "https://www.bmwgroup.com/"
                }
            ]
        },
        "bayer": {
            "type": "company",
            "country": "germany",
            "name": "Bayer AG",
            "summary": "Bayer AG is a German multinational pharmaceutical and biotechnology company and is one of the largest pharmaceutical companies and biomedical companies in the world. Headquartered in Leverkusen, Bayer's areas of business include pharmaceuticals, consumer healthcare products, agricultural chemicals, seeds and biotechnology products. The company is a component of the EURO STOXX 50 stock market index.",
            "ticker": "BAYN",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Bayer AG",
                    "url": "https://en.wikipedia.org/wiki/Bayer"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "beiersdorf": {
            "type": "company",
            "country": "germany",
            "name": "Beiersdorf AG",
            "summary": "Beiersdorf AG is a German multinational company that manufactures personal-care products and pressure-sensitive adhesives headquartered in Hamburg, Germany. Its brands include Elastoplast, Eucerin, Aquaphor, Labello, La Prairie, Nivea, Coppertone and Tesa.",
            "ticker": "BEI",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Beiersdorf AG",
                    "url": "https://en.wikipedia.org/wiki/Beiersdorf"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "brenntag": {
            "type": "company",
            "country": "germany",
            "name": "Brenntag SE",
            "summary": "Brenntag SE is the holding company of Brenntag Group. The company was founded in 1874 in Berlin and specializes in the distribution of chemicals and ingredients. The company is headquartered in Essen, Germany and has operations in more than 600 locations in 72 countries.",
            "ticker": "BNR",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "1395",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Brenntag SE",
                    "url": "https://en.wikipedia.org/wiki/Brenntag"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "commerzbank": {
            "type": "company",
            "country": "germany",
            "name": "Commerzbank AG",
            "summary": "The Commerzbank Aktiengesellschaft is a European banking institution headquartered in Frankfurt am Main, Hesse, Germany. It offers services to private, business and corporate customers. The Commerzbank Group also includes the Polish subsidiary mBank.",
            "ticker": "CBK",
            "exchange": "",
            "sector": "petroleum industry",
            "headquarters": "London",
            "founded": "1890",
            "employees": "92,000",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "compensation": {
                "ceeName": "Ben van Beurden",
                "ceoTitle": null,
                "ceoTotal": null,
                "ceoSalary": null,
                "ceoEquity": null,
                "medianWorker": null,
                "ceoWorkerRatio": null,
                "source": "Wikipedia / Wikidata",
                "url": "https://en.wikipedia.org/wiki/Commerzbank"
            },
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Commerzbank AG",
                    "url": "https://en.wikipedia.org/wiki/Commerzbank"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Commerzbank AG — official website",
                    "url": "https://www.shell.com/"
                }
            ]
        },
        "continental": {
            "type": "company",
            "country": "germany",
            "name": "Continental AG",
            "summary": "Continental AG, commonly known as Continental and colloquially as Conti, is a German multinational manufacturing company. Headquartered in Hanover, Lower Saxony, it is one of the world's leading tire manufacturers. Following the spin-off of its automotive technology division as Aumovio in 2025, Continental now focuses on two core businesses: Tires and ContiTech.",
            "ticker": "CON",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Continental AG",
                    "url": "https://en.wikipedia.org/wiki/Continental%20AG"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "covestro": {
            "type": "company",
            "country": "germany",
            "name": "Covestro AG",
            "summary": "Covestro AG is a German company producing polyurethane and polycarbonate raw materials. Products include isocyanates and polyols for cellular foams, thermoplastic polyurethane and polycarbonate pellets, as well as polyurethane based additives used in the formulation of coatings and adhesives. It is a Bayer spin-off formed in the fall of 2015 and was formerly called Bayer MaterialScience.",
            "ticker": "1COV",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "1967",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Covestro AG",
                    "url": "https://en.wikipedia.org/wiki/Covestro"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "daimler-truck": {
            "type": "company",
            "country": "germany",
            "name": "Daimler Truck Holding AG",
            "summary": "Daimler Truck AG is the world's largest commercial vehicle manufacturer, with over 35 main locations worldwide and approximately 100,000 employees. Daimler Truck AG is headquartered in Leinfelden-Echterdingen, Germany. It was a part of Daimler AG from November 2019 to December 2021.",
            "ticker": "DTG",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Daimler Truck Holding AG",
                    "url": "https://en.wikipedia.org/wiki/Daimler%20Truck"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "deutsche-bank": {
            "type": "company",
            "country": "germany",
            "name": "Deutsche Bank AG",
            "summary": "Deutsche Bank AG is a German multinational investment bank and financial services company headquartered in Frankfurt. It is dual-listed on the Frankfurt Stock Exchange and the New York Stock Exchange.",
            "ticker": "DBK",
            "exchange": "",
            "sector": "financial services",
            "headquarters": "Frankfurt",
            "founded": "1870",
            "employees": "97,535",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "compensation": {
                "ceeName": "Christian Sewing",
                "ceoTitle": null,
                "ceoTotal": null,
                "ceoSalary": null,
                "ceoEquity": null,
                "medianWorker": null,
                "ceoWorkerRatio": null,
                "source": "Wikipedia / Wikidata",
                "url": "https://en.wikipedia.org/wiki/Deutsche%20Bank"
            },
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Deutsche Bank AG",
                    "url": "https://en.wikipedia.org/wiki/Deutsche%20Bank"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Deutsche Bank AG — official website",
                    "url": "https://www.db.com"
                }
            ]
        },
        "deutsche-boerse": {
            "type": "company",
            "country": "germany",
            "name": "Deutsche Boerse AG",
            "summary": "Deutsche Börse AG, or the Deutsche Börse Group, is a German multinational corporation that offers a marketplace for organizing the trading of shares and other securities. It is also a transaction services provider, giving companies and investors access to global capital markets. Founded in 1992, it is a joint stock company headquartered in Frankfurt. It is the third-largest stock market in Europe by market cap after Euronext Paris and the London Stock Exchange.",
            "ticker": "DB1",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "1841",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Deutsche Boerse AG",
                    "url": "https://en.wikipedia.org/wiki/Deutsche%20B%C3%B6rse"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Deutsche Boerse AG — official website",
                    "url": "http://www.grundycountymo.com"
                }
            ]
        },
        "deutsche-post": {
            "type": "company",
            "country": "germany",
            "name": "Deutsche Post AG",
            "summary": "Deutsche Post is a DHL Group brand,, used for its domestic mail services in Germany. The services offered under the brand are those of a traditional mail service, making the brand the successor of the former state-owned mail monopoly, Deutsche Bundespost. Deutsche Post's monopoly on these services expired in 2008.",
            "ticker": "DHL",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Deutsche Post AG",
                    "url": "https://en.wikipedia.org/wiki/Deutsche%20Post"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Deutsche Post AG — official website",
                    "url": "https://www.comune.marcianamarina.li.it/"
                }
            ]
        },
        "deutsche-telekom": {
            "type": "company",
            "country": "germany",
            "name": "Deutsche Telekom AG",
            "summary": "Deutsche Telekom AG is a partially state-owned German telecommunications company headquartered in Bonn and is Europe's largest telecommunications provider by revenue. It was formed in 1995 when Deutsche Bundespost, a state monopoly at the time, was restructured. Since then, Deutsche Telekom has consistently featured among Fortune Magazine's top Global 500 companies by revenue, with its ranking as of 2023 at number 79. In 2023, the company was ranked 41st in the Forbes Global 2000. The company operates several subsidiaries worldwide, including the mobile communications brand T-Mobile. It is the",
            "ticker": "DTE",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Deutsche Telekom AG",
                    "url": "https://en.wikipedia.org/wiki/Deutsche%20Telekom"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "porsche-ag": {
            "type": "company",
            "country": "germany",
            "name": "Dr. Ing. h.c. F. Porsche AG",
            "summary": "Dr. Ing. h.c. F. Porsche AG, commonly known as Porsche, is a German automobile manufacturer specializing in luxury, high-performance sports cars, SUVs and sedans, headquartered in Stuttgart, Baden-Württemberg, Germany. The company is owned by Volkswagen AG, a controlling stake of which is owned by Porsche Automobil Holding SE, usually shortened to Porsche SE. Porsche's current lineup includes the 911, Panamera, Macan, Cayenne, and Taycan.",
            "ticker": "P911",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Dr. Ing. h.c. F. Porsche AG",
                    "url": "https://en.wikipedia.org/wiki/Porsche"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "eon": {
            "type": "company",
            "country": "germany",
            "name": "E.ON SE",
            "summary": "E.ON SE is a German multinational electric utility company based in Essen, Germany. It operates as one of the world's largest investor-owned electric utility service providers. The name originates from the Latin word aeon, derived from the Greek αἰών aion, which means age or \"infinity\", with the period being added to create secondary meanings of \"energy\" (E) and \"illumination\" (ON). The company is a component of the DAX stock index.",
            "ticker": "EOAN",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — E.ON SE",
                    "url": "https://en.wikipedia.org/wiki/E.ON"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "E.ON SE — official website",
                    "url": "https://www.hickenlooper.com/"
                }
            ]
        },
        "fresenius": {
            "type": "company",
            "country": "germany",
            "name": "Fresenius SE & Co. KGaA",
            "summary": "Fresenius is a German surname. Notable people with the surname include:Carl Remigius Fresenius (1818–1897), German chemist\nChristian Fresenius (1749-1811), German Jurist and writer\nEduard Fresenius (, German businessman, founder of Fresenius\nGeorg Fresenius, German botanist\nWilhelm Fresenius, German chemist from Mainz",
            "ticker": "FRE",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Fresenius SE & Co. KGaA",
                    "url": "https://en.wikipedia.org/wiki/Fresenius"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Fresenius SE & Co. KGaA — official website",
                    "url": "http://www.kurfurstova.com/"
                }
            ]
        },
        "hannover-re": {
            "type": "company",
            "country": "germany",
            "name": "Hannover Re SE",
            "summary": "Hannover Re is a reinsurance company based in Hannover, Germany. It is the third-largest reinsurance group in the world, with a gross premium of around €33 billion. Founded in 1966, Hannover Re transacts all lines of property & casualty and life & health reinsurance and has a network of over 170 subsidiaries, branches and representative offices on all five continents with a total staff of more than 3,000. The Group's German property and casualty business is written by the subsidiary E+S Rück.",
            "ticker": "HNR1",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Hannover Re SE",
                    "url": "https://en.wikipedia.org/wiki/Hannover%20Re"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "henkel": {
            "type": "company",
            "country": "germany",
            "name": "Henkel AG & Co. KGaA",
            "summary": "Henkel AG & Co. KGaA, commonly known as Henkel, is a German multinational chemical and consumer goods company headquartered in Düsseldorf, Germany. Founded in 1876, the DAX company is organized into two globally operating business units and is known for brands such as Loctite, Persil, Fa, Pritt, Dial and Purex.",
            "ticker": "HEN3",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Henkel AG & Co. KGaA",
                    "url": "https://en.wikipedia.org/wiki/Henkel"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "infineon": {
            "type": "company",
            "country": "germany",
            "name": "Infineon Technologies AG",
            "summary": "Infineon Technologies AG is a German company which designs and manufactures semiconductor devices. It provides parts for automotive, power and security systems. In 2023, Infineon was Germany's largest chip manufacturer, and had roughly 57,000 employees in 2025.",
            "ticker": "IFX",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Infineon Technologies AG",
                    "url": "https://en.wikipedia.org/wiki/Infineon%20Technologies"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Infineon Technologies AG — official website",
                    "url": "http://www.pepe-sanchez.com"
                }
            ]
        },
        "mtu-aero": {
            "type": "company",
            "country": "germany",
            "name": "MTU Aero Engines AG",
            "summary": "MTU Aero Engines AG is a German aircraft engine manufacturer. MTU develops, manufactures and provides service support for military and civil aircraft engines. MTU Aero Engines was formerly known as MTU München.",
            "ticker": "MTX",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — MTU Aero Engines AG",
                    "url": "https://en.wikipedia.org/wiki/MTU%20Aero%20Engines"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "mercedes-benz": {
            "type": "company",
            "country": "germany",
            "name": "Mercedes-Benz Group AG",
            "summary": "Mercedes-Benz Group AG is a German multinational automotive company headquartered in Stuttgart, Baden-Württemberg, Germany. It is one of the world's leading car manufacturers. Daimler-Benz was formed with the merger of Benz & Cie., the world's oldest car company, and Daimler Motoren Gesellschaft in 1926. The company was renamed DaimlerChrysler upon the acquisition of the American automobile manufacturer, Chrysler Corporation in 1998, it was renamed to Daimler upon the divestment of Chrysler in 2007. In 2021, Daimler was the second-largest German automaker and the sixth-largest worldwide by pro",
            "ticker": "MBG",
            "exchange": "",
            "sector": "automotive industry",
            "headquarters": "Detroit",
            "founded": "1908",
            "employees": "164,000",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "compensation": {
                "ceeName": "Mary Barra",
                "ceoTitle": null,
                "ceoTotal": null,
                "ceoSalary": null,
                "ceoEquity": null,
                "medianWorker": null,
                "ceoWorkerRatio": null,
                "source": "Wikipedia / Wikidata",
                "url": "https://en.wikipedia.org/wiki/Mercedes-Benz%20Group"
            },
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Mercedes-Benz Group AG",
                    "url": "https://en.wikipedia.org/wiki/Mercedes-Benz%20Group"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Mercedes-Benz Group AG — official website",
                    "url": "https://www.gm.com/"
                }
            ]
        },
        "merck-kgaa": {
            "type": "company",
            "country": "germany",
            "name": "Merck KGaA",
            "summary": "The Merck Group, branded and commonly known as Merck, is a German multinational science and technology company headquartered in Darmstadt, with about 60,000 employees and a presence in 66 countries. The group includes around 250 companies; the main company is Merck KGaA in Germany. The company is divided into three business lines: Healthcare, Life Sciences and Electronics. Merck was founded in 1668 and is the world's oldest operating chemical and pharmaceutical company, as well as one of the largest pharmaceutical companies globally.",
            "ticker": "MRK",
            "exchange": "",
            "sector": "retail",
            "headquarters": "City of London",
            "founded": "1869",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "compensation": {
                "ceeName": "Mike Coupe",
                "ceoTitle": null,
                "ceoTotal": null,
                "ceoSalary": null,
                "ceoEquity": null,
                "medianWorker": null,
                "ceoWorkerRatio": null,
                "source": "Wikipedia / Wikidata",
                "url": "https://en.wikipedia.org/wiki/Merck%20Group"
            },
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Merck KGaA",
                    "url": "https://en.wikipedia.org/wiki/Merck%20Group"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Merck KGaA — official website",
                    "url": "https://www.sainsburys.co.uk/"
                }
            ]
        },
        "munich-re": {
            "type": "company",
            "country": "germany",
            "name": "Muenchener Rueckversicherungs-Gesellschaft AG",
            "summary": "Munich Re Group or Munich Reinsurance Company is a German multinational insurance company based in Munich, Germany. It is the world's largest reinsurer. ERGO, a subsidiary of Munich Re, serves as the primary insurance arm of the Group. Munich Re's shares are publicly listed. Munich Re is included in the DAX index at the Frankfurt Stock Exchange, the Euro Stoxx 50, and other indices.",
            "ticker": "MUV2",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Muenchener Rueckversicherungs-Gesellschaft AG",
                    "url": "https://en.wikipedia.org/wiki/Munich%20Re"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "porsche-se": {
            "type": "company",
            "country": "germany",
            "name": "Porsche Automobil Holding SE",
            "summary": "Porsche Automobil Holding SE, trading as Porsche SE, is a German multinational corporation primarily known as a holding company of Volkswagen Group with investments in the automotive industry. Porsche SE is headquartered in Zuffenhausen, a city district of Stuttgart, Baden-Württemberg, and is majority owned by the Austrian-German Porsche–Piëch family. The company was founded in Stuttgart as Dr. Ing. h.c. F. Porsche GmbH in 1931 by Ferdinand Porsche (1875–1951) and his son-in-law Anton Piëch (1894–1952).",
            "ticker": "PAH3",
            "exchange": "",
            "sector": "—",
            "headquarters": "Germany",
            "founded": "",
            "employees": "",
            "revenue": "",
            "marketCap": "",
            "shareholders": [],
            "lobbying": [],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations.",
                "source": "Parteiengesetz §25",
                "url": "https://www.gesetze-im-internet.de/partg/__25.html"
            },
            "fines": [],
            "labor": [],
            "competitors": [],
            "sources": [
                {
                    "title": "Wikipedia — Porsche Automobil Holding SE",
                    "url": "https://en.wikipedia.org/wiki/Porsche%20SE"
                },
                {
                    "title": "Bundesanzeiger — annual report filings",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "BaFin — voting rights notifications",
                    "url": "https://www.bafin.de"
                }
            ]
        },
        "sap": {
            "type": "company",
            "country": "germany",
            "name": "SAP SE",
            "summary": "SAP SE is the world's leading enterprise application software company, with customers in over 180 countries. Co-founded in 1972 by Hasso Plattner and colleagues as a spin-off from IBM Germany.",
            "ticker": "SAP",
            "exchange": "XETRA / NYSE (ADR)",
            "sector": "Enterprise Software / Technology",
            "headquarters": "Walldorf, Baden-Württemberg, Germany",
            "founded": "1972",
            "employees": "107,000",
            "revenue": "€31.2 billion (2023)",
            "marketCap": "~€230 billion",
            "shareholders": [
                {
                    "name": "Hasso Plattner (+ HHP Research Foundation)",
                    "stake": "~9.5%",
                    "type": "Co-Founder",
                    "source": "SAP SE Annual Report 2023 / Bundesanzeiger",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "name": "Vanguard Group",
                    "stake": "~4.8%",
                    "type": "Institutional",
                    "source": "BaFin voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "BlackRock Inc.",
                    "stake": "~4.0%",
                    "type": "Institutional",
                    "source": "BaFin voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "Free float",
                    "stake": "~78%",
                    "type": "Public",
                    "source": "SAP SE Investor Relations",
                    "url": "https://www.sap.com/investors.html"
                }
            ],
            "compensation": {
                "ceeName": "Christian Klein",
                "ceoTitle": "Chief Executive Officer (Vorstandsvorsitzender)",
                "ceoTotal": "€12.8M",
                "ceoSalary": "€900K",
                "ceoEquity": "€10.2M (performance shares + RSUs)",
                "medianWorker": "~€95,000",
                "ceoWorkerRatio": "~135:1",
                "source": "SAP SE Annual Report 2023 (Remuneration Report)",
                "url": "https://www.sap.com/investors/en/reports.html"
            },
            "lobbying": [
                {
                    "year": "2024",
                    "amount": "€3.3M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "year": "2023",
                    "amount": "€2.9M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "year": "2022",
                    "amount": "€2.4M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                }
            ],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "SAP lobbies through BITKOM and DIGITALEUROPE. Key topics: AI Act, data regulation.",
                "source": "Parteiengesetz §25 / BITKOM / Bundestag Lobbyregister",
                "url": "https://lobbyregister.bundestag.de"
            },
            "fines": [
                {
                    "year": "2024",
                    "description": "SAP agreed to pay ~$222M to resolve U.S. DOJ FCPA investigation: bribery of government officials in South Africa, Malawi, Tanzania, Ghana, Indonesia, and Panama.",
                    "source": "U.S. DOJ / SEC (January 2024)",
                    "url": "https://www.justice.gov/opa/pr/sap-agrees-pay-over-220-million-resolve-foreign-corrupt-practices-act-charges"
                }
            ],
            "labor": [
                {
                    "description": "SAP announced global restructuring affecting ~8,000 employees (7.5% of workforce) in January 2024, shifting resources toward AI.",
                    "source": "SAP press release / Handelsblatt (2024)",
                    "url": "https://news.sap.com"
                }
            ],
            "competitors": [
                "Oracle Corp. (ORCL, NYSE)",
                "Microsoft Dynamics",
                "Salesforce (CRM)",
                "Workday (WDAY)"
            ],
            "sources": [
                {
                    "title": "SAP SE Annual Report 2023",
                    "url": "https://www.sap.com/investors/en/reports.html"
                },
                {
                    "title": "Bundestag Lobbyregister — SAP SE",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "title": "U.S. DOJ — SAP FCPA settlement (2024)",
                    "url": "https://www.justice.gov/opa/pr/sap-agrees-pay-over-220-million-resolve-foreign-corrupt-practices-act-charges"
                }
            ]
        },
        "volkswagen": {
            "type": "company",
            "country": "germany",
            "name": "Volkswagen AG",
            "summary": "Volkswagen AG is Europe's largest automaker and one of the world's largest by vehicle sales. Its brands include VW, Audi, Porsche, SEAT, Skoda, Lamborghini, Bentley, and MAN. The German state of Lower Saxony holds a blocking minority stake under the VW Law (Volkswagen-Gesetz).",
            "ticker": "VOW3",
            "exchange": "XETRA / Frankfurt Stock Exchange",
            "sector": "Automotive",
            "headquarters": "Wolfsburg, Lower Saxony, Germany",
            "founded": "1937",
            "employees": "684,000",
            "revenue": "€293 billion (2023)",
            "marketCap": "~€55 billion",
            "shareholders": [
                {
                    "name": "Porsche Automobil Holding SE",
                    "stake": "53.3% (voting)",
                    "type": "Family / Strategic (Piech & Porsche families)",
                    "source": "Volkswagen AG Annual Report 2023 / Bundesanzeiger",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "name": "State of Lower Saxony (Niedersachsen)",
                    "stake": "11.8% (blocking minority)",
                    "type": "Government / Public Entity",
                    "source": "Volkswagen AG Annual Report 2023",
                    "url": "https://annualreport2023.volkswagen-group.com"
                },
                {
                    "name": "Qatar Investment Authority",
                    "stake": "14.6%",
                    "type": "Sovereign Wealth Fund",
                    "source": "VW Annual Report 2023 / BaFin",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "Vanguard Group",
                    "stake": "~1.5% (ordinary shares)",
                    "type": "Institutional",
                    "source": "BaFin voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "Free float",
                    "stake": "~18.8%",
                    "type": "Public",
                    "source": "Volkswagen AG Investor Relations",
                    "url": "https://www.volkswagenag.com/en/InvestorRelations.html"
                }
            ],
            "compensation": {
                "ceeName": "Oliver Blume",
                "ceoTitle": "Chairman of the Board of Management",
                "ceoTotal": "€10.3M",
                "ceoSalary": "€1.3M",
                "ceoEquity": "€6.2M (long-term incentive)",
                "medianWorker": "~€62,000",
                "ceoWorkerRatio": "~166:1",
                "source": "Volkswagen AG Geschäftsbericht 2023 (Vergütungsbericht)",
                "url": "https://annualreport2023.volkswagen-group.com"
            },
            "lobbying": [
                {
                    "year": "2024",
                    "amount": "€6.2M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "year": "2023",
                    "amount": "€5.8M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "year": "2022",
                    "amount": "€4.9M",
                    "source": "Bundestag Lobbyregister",
                    "url": "https://lobbyregister.bundestag.de"
                }
            ],
            "politicalSpending": {
                "pac": "N/A — prohibited by Parteiengesetz §25",
                "total2023": "€0",
                "note": "German law (Parteiengesetz §25) prohibits direct donations to political parties from corporations. VW engages through VDA (Verband der Automobilindustrie).",
                "source": "Parteiengesetz §25 / Bundestag Lobbyregister",
                "url": "https://lobbyregister.bundestag.de"
            },
            "fines": [
                {
                    "year": "2015–2021",
                    "description": "Dieselgate: VW admitted to defeat devices in ~11M diesel vehicles. Total costs >€30 billion globally.",
                    "source": "U.S. DOJ / Staatsanwaltschaft Braunschweig",
                    "url": "https://www.justice.gov/opa/pr/volkswagen-ag-agrees-plead-guilty-and-pay-43-billion-connection-allegations-conspiracy-and"
                }
            ],
            "labor": [
                {
                    "description": "VW has full co-determination (Mitbestimmung): Supervisory Board is 50% employee representatives. IG Metall holds several seats.",
                    "source": "VW Corporate Governance / IG Metall",
                    "url": "https://www.igmetall.de"
                },
                {
                    "description": "In 2024, VW announced closure of at least three German plants and 35,000+ job cuts. IG Metall launched strikes.",
                    "source": "Handelsblatt / Reuters (2024)",
                    "url": "https://www.handelsblatt.com"
                }
            ],
            "competitors": [
                "BMW AG (BMW, XETRA)",
                "Mercedes-Benz Group AG (MBG, XETRA)",
                "Stellantis N.V. (STLA)",
                "Toyota Motor Corp.",
                "Renault Group"
            ],
            "sources": [
                {
                    "title": "Volkswagen AG Annual Report 2023",
                    "url": "https://annualreport2023.volkswagen-group.com"
                },
                {
                    "title": "Bundestag Lobbyregister — Volkswagen AG",
                    "url": "https://lobbyregister.bundestag.de"
                },
                {
                    "title": "BaFin — VW voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "U.S. DOJ — Volkswagen Dieselgate plea",
                    "url": "https://www.justice.gov/opa/pr/volkswagen-ag-agrees-plead-guilty-and-pay-43-billion-connection-allegations-conspiracy-and"
                }
            ]
        },
        "dieter-schwarz": {
            "type": "person",
            "country": "germany",
            "name": "Dieter Schwarz",
            "summary": "Dieter Schwarz owns 100% of the Schwarz Group — parent of Lidl (~12,000 stores, 31 countries) and Kaufland. Neither company is publicly listed. Schwarz has never given a public interview.",
            "title": "Owner, Schwarz Group (Lidl & Kaufland)",
            "nationality": "German",
            "born": "1939",
            "netWorth": "€47 billion (~$51B)",
            "netWorthRank": "#1 wealthiest in Germany",
            "netWorthSource": "Manager Magazin Reichenliste 2024",
            "netWorthUrl": "https://www.manager-magazin.de/finanzen/reichenliste/",
            "assets": [
                {
                    "name": "Schwarz Group (Lidl + Kaufland)",
                    "description": "100% private. Combined revenue: ~€150 billion (2023). Europe's largest retailer by revenue.",
                    "source": "Bundesanzeiger / Manager Magazin estimates",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "name": "Dieter Schwarz Stiftung",
                    "description": "Foundation funding Technische Hochschule Heilbronn and regional education projects. Assets: ~€5B+.",
                    "source": "Dieter Schwarz Stiftung",
                    "url": "https://www.dieter-schwarz-stiftung.de"
                }
            ],
            "boardMemberships": [
                {
                    "org": "Schwarz Group",
                    "role": "Sole owner (no public board)",
                    "source": "Schwarz Gruppe / Bundesanzeiger"
                }
            ],
            "foundations": [
                {
                    "name": "Dieter Schwarz Stiftung",
                    "description": "Funds Technische Hochschule Heilbronn, Bildungscampus Heilbronn (€600M+ campus), and social welfare.",
                    "source": "Dieter Schwarz Stiftung",
                    "url": "https://www.dieter-schwarz-stiftung.de"
                }
            ],
            "politicalSpending": {
                "pac": "None",
                "summary": "No documented political donations. German law prohibits corporate party donations. Schwarz is intensely private.",
                "total2024": null,
                "source": "Parteiengesetz §25 / no public records",
                "url": "https://lobbyregister.bundestag.de"
            },
            "timeline": [
                {
                    "year": "1963",
                    "event": "Joins father Josef Schwarz's wholesale food company in Heilbronn."
                },
                {
                    "year": "1973",
                    "event": "Opens first Lidl store in Ludwigshafen, modelled on Aldi's discount concept."
                },
                {
                    "year": "1988",
                    "event": "Lidl expands into France — beginning European rollout."
                },
                {
                    "year": "2000",
                    "event": "Schwarz Group becomes Germany's largest food retailer."
                },
                {
                    "year": "2015",
                    "event": "Lidl enters the U.S. market."
                },
                {
                    "year": "2024",
                    "event": "Schwarz Group revenue surpasses €150B — Europe's largest retailer."
                }
            ],
            "sources": [
                {
                    "title": "Manager Magazin Reichenliste 2024",
                    "url": "https://www.manager-magazin.de/finanzen/reichenliste/"
                },
                {
                    "title": "Bundesanzeiger — Schwarz Gruppe filings (limited)",
                    "url": "https://www.bundesanzeiger.de"
                },
                {
                    "title": "Dieter Schwarz Stiftung",
                    "url": "https://www.dieter-schwarz-stiftung.de"
                }
            ]
        },
        "hasso-plattner": {
            "type": "person",
            "country": "germany",
            "name": "Hasso Plattner",
            "summary": "Hasso Plattner co-founded SAP SE in 1972 with four IBM Germany colleagues. He chairs the Supervisory Board and holds ~9.5% of SAP shares (via personal holdings and HHP Research Foundation). He founded and endowed the Hasso Plattner Institute (HPI) at the University of Potsdam.",
            "title": "Co-founder & Supervisory Board Chairman, SAP SE",
            "nationality": "German",
            "born": "1944",
            "netWorth": "€14 billion (~$15B)",
            "netWorthRank": "Top 10 wealthiest in Germany",
            "netWorthSource": "Manager Magazin Reichenliste 2024",
            "netWorthUrl": "https://www.manager-magazin.de/finanzen/reichenliste/",
            "assets": [
                {
                    "name": "SAP SE (~9.5% stake)",
                    "description": "Worth ~€22B at peak SAP market cap (~€230B, 2024).",
                    "source": "SAP SE Annual Report 2023 / BaFin",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "Hasso Plattner Institute (HPI), Potsdam",
                    "description": "Germany's leading IT institute, co-located with University of Potsdam. Plattner donated €100M+ in initial endowment.",
                    "source": "HPI official website",
                    "url": "https://hpi.de"
                }
            ],
            "boardMemberships": [
                {
                    "org": "SAP SE",
                    "role": "Chairman of the Supervisory Board",
                    "source": "SAP SE Annual Report 2023"
                }
            ],
            "foundations": [
                {
                    "name": "Hasso Plattner Foundation",
                    "description": "Funds HPI Potsdam and HPI School of Design Thinking. Total donations exceed €700M.",
                    "source": "HPI / Hasso Plattner Foundation",
                    "url": "https://hpi.de/en/about-hpi/hasso-plattner.html"
                }
            ],
            "politicalSpending": {
                "pac": "None",
                "summary": "No documented political donations. Influence operates through SAP, HPI, and BITKOM.",
                "total2024": null,
                "source": "No public records",
                "url": "https://lobbyregister.bundestag.de"
            },
            "timeline": [
                {
                    "year": "1968",
                    "event": "Joins IBM Germany in Mannheim."
                },
                {
                    "year": "1972",
                    "event": "Co-founds SAP with four IBM colleagues in Weinheim."
                },
                {
                    "year": "1998",
                    "event": "Founds and endows the Hasso Plattner Institute at University of Potsdam."
                },
                {
                    "year": "2003",
                    "event": "Steps down as SAP co-CEO; becomes Supervisory Board Chairman."
                },
                {
                    "year": "2010",
                    "event": "SAP launches HANA (in-memory database) — Plattner's core architectural concept."
                },
                {
                    "year": "2023",
                    "event": "SAP market cap surpasses €200B — Europe's most valuable software company."
                }
            ],
            "sources": [
                {
                    "title": "Manager Magazin Reichenliste 2024",
                    "url": "https://www.manager-magazin.de/finanzen/reichenliste/"
                },
                {
                    "title": "SAP SE Annual Report 2023",
                    "url": "https://www.sap.com/investors/en/reports.html"
                },
                {
                    "title": "Hasso Plattner Institute — About",
                    "url": "https://hpi.de/en/about-hpi/hasso-plattner.html"
                }
            ]
        },
        "susanne-klatten": {
            "type": "person",
            "country": "germany",
            "name": "Susanne Klatten",
            "summary": "Susanne Klatten is the daughter of Herbert Quandt, who rescued BMW from bankruptcy in 1959. Together with her brother Stefan Quandt, she controls ~45% of BMW AG. She also holds a majority stake in specialty chemicals company Altana AG.",
            "title": "Billionaire investor; 19.2% stake in BMW AG; majority owner of Altana AG",
            "nationality": "German",
            "born": "1962",
            "netWorth": "€27 billion (~$29B)",
            "netWorthRank": "#2 wealthiest woman in Germany",
            "netWorthSource": "Manager Magazin Reichenliste 2024",
            "netWorthUrl": "https://www.manager-magazin.de/finanzen/reichenliste/",
            "assets": [
                {
                    "name": "BMW AG (BMW, XETRA)",
                    "description": "19.2% stake — ~€12B at 2024 market prices.",
                    "source": "BMW AG Annual Report 2023 / BaFin",
                    "url": "https://www.bafin.de"
                },
                {
                    "name": "Altana AG (majority stake via SKion GmbH)",
                    "description": "Leading specialty chemicals company. EBITDA ~€600M. Privately held.",
                    "source": "Bundesanzeiger / Altana AG",
                    "url": "https://www.altana.de"
                },
                {
                    "name": "SKion GmbH",
                    "description": "Personal holding company for all industrial and financial investments.",
                    "source": "Bundesanzeiger",
                    "url": "https://www.bundesanzeiger.de"
                }
            ],
            "boardMemberships": [
                {
                    "org": "BMW AG",
                    "role": "Member of the Supervisory Board (shareholder side)",
                    "source": "BMW AG Annual Report 2023"
                },
                {
                    "org": "Altana AG",
                    "role": "Majority owner and Supervisory Board member",
                    "source": "Altana AG"
                }
            ],
            "foundations": [
                {
                    "name": "Philanthropic activity via SKion GmbH (informal)",
                    "description": "Donates to medical research (bone marrow, cancer) and arts organisations. No major named foundation.",
                    "source": "Manager Magazin",
                    "url": "https://www.manager-magazin.de"
                }
            ],
            "politicalSpending": {
                "pac": "None",
                "summary": "No documented political donations. German law prohibits corporate party donations.",
                "total2024": null,
                "source": "Parteiengesetz §25 / no public records",
                "url": "https://lobbyregister.bundestag.de"
            },
            "timeline": [
                {
                    "year": "1962",
                    "event": "Born in Munich to Herbert and Johanna Quandt."
                },
                {
                    "year": "1982",
                    "event": "Studies business under a pseudonym to avoid media attention."
                },
                {
                    "year": "1997",
                    "event": "Joins the BMW Supervisory Board."
                },
                {
                    "year": "2003",
                    "event": "Takes majority control of Altana AG."
                },
                {
                    "year": "2008",
                    "event": "Subject of blackmail by fraudster Helg Sgarbi; resulting criminal conviction."
                },
                {
                    "year": "2016",
                    "event": "Named Germany's wealthiest woman by Manager Magazin."
                },
                {
                    "year": "2023",
                    "event": "BMW Group reports record profits; BMW stake exceeds €11B."
                }
            ],
            "sources": [
                {
                    "title": "Manager Magazin Reichenliste 2024",
                    "url": "https://www.manager-magazin.de/finanzen/reichenliste/"
                },
                {
                    "title": "BMW AG Annual Report 2023",
                    "url": "https://www.bmwgroup.com/en/investor-relations/financial-reports.html"
                },
                {
                    "title": "BaFin — BMW voting rights notifications",
                    "url": "https://www.bafin.de"
                },
                {
                    "title": "Forbes — Susanne Klatten",
                    "url": "https://www.forbes.com/profile/susanne-klatten/"
                }
            ]
        }
    },
    "factCards": [
        {
            "category": "CEO Pay · Germany",
            "headline": "The average DAX 40 CEO earns approximately 50× the median German worker's wage.",
            "detail": "Average total compensation for a DAX 40 CEO was €7.8M in 2022, vs. a median German worker wage of ~€40,500. Germany's ratio is lower than the U.S. S&P 500 average (272×) due to co-determination laws and collective bargaining.",
            "source": "DSW / Handelsblatt CEO pay study 2023 / Statista",
            "url": "https://www.statista.com/statistics/462682/germany-average-wages/"
        },
        {
            "category": "Lobbying · Germany",
            "headline": "Germany's mandatory Bundestag Lobby Register launched in 2022. Over 6,000 organisations are registered.",
            "detail": "The Lobbyregistergesetz (mandatory lobbying registration law) came into force in January 2022. Organisations must disclose lobbying budget, number of lobbyists, and covered issues. BDI and VDA are among the largest registered spenders.",
            "source": "Bundestag Lobbyregister / Lobbycontrol e.V.",
            "url": "https://lobbyregister.bundestag.de"
        },
        {
            "category": "Corporate Ownership · Germany",
            "headline": "German law prohibits corporations from donating directly to political parties.",
            "detail": "Parteiengesetz §25 prohibits donations from public companies, state-adjacent entities, and organisations significantly publicly funded. Individual donations over €10,000 must be published; over €50,000 must be published immediately.",
            "source": "Parteiengesetz §25 / Bundeszentrale für politische Bildung",
            "url": "https://www.gesetze-im-internet.de/partg/__25.html"
        },
        {
            "category": "Quandt Family · BMW",
            "headline": "The Quandt siblings control 45% of BMW AG — worth over €27 billion combined.",
            "detail": "Stefan Quandt (25.8%) and Susanne Klatten (19.2%) control a blocking minority in BMW AG. Their father Herbert Quandt rescued BMW from bankruptcy in 1959 by acquiring his majority stake.",
            "source": "BMW AG Annual Report 2023 / Manager Magazin",
            "url": "https://www.bmwgroup.com/en/investor-relations/financial-reports.html"
        },
        {
            "category": "Dieselgate · Volkswagen",
            "headline": "VW's emissions scandal cost over €30 billion in fines, settlements, and remediation.",
            "detail": "In 2015, Volkswagen admitted to defeat devices in ~11M diesel vehicles. Total cost >€30B globally: $2.8B U.S. criminal fine, $1.5B civil settlement, €1B German fine.",
            "source": "U.S. DOJ / Staatsanwaltschaft Braunschweig / Reuters",
            "url": "https://www.justice.gov/opa/pr/volkswagen-ag-agrees-plead-guilty-and-pay-43-billion-connection-allegations-conspiracy-and"
        },
        {
            "category": "State Ownership · Germany",
            "headline": "The German Federal Government owns approximately 27.8% of Deutsche Telekom.",
            "detail": "Deutsche Telekom was privatised from Deutsche Bundespost in 1995, but the Federal Government retained its stake via KfW Bankengruppe. Germany also holds direct or indirect majority stakes in Deutsche Post, Deutsche Bahn, and partial stakes in Lufthansa.",
            "source": "Beteiligungsbericht des Bundes / Bundesministerium der Finanzen",
            "url": "https://www.bundesregierung.de"
        }
    ]
};
